lively.components/window.js
lively.ide/world-commands.js
lively.ide/world.js

Hi,
I added some ease-of-use menu items, the screenshots should be self-explanatory.
Naturally, I am absolutely open to any criticism!
I could also imagine elaborating on this functionality, e.g. "close all other browsers" in browsers, workspaces,... if that is something that would be nice.
I plan on investigating the whole world-menu to get more accustomed to `lively` and maybe fix some things that are broken right now, however I think this change stands for its own, although it touches the world menu.

add menu to close/minimize multiple windows

---

lively.morphic/text/document.js

In the text/document.js row can't be a const, because it is changed in line 1435. This is a hotfix which solves the problem.

Hotfix: enable copying in browser

---

lively.halos/morph.js

In a user study, we found the "Times" icon in a Morph' shalo not to be clear enough about deleting the whole Morph. That's why we replaced the icon with a "Trash" icon.

Use trash icon for CloseHaloItem

---

lively.ide/js/browser/index.js
lively.ide/js/inspector.js
lively.ide/js/objecteditor/index.js
lively.ide/js/workspace.js
lively.ide/world.js
lively.morphic/morph.js

Browser, Object Editor, JS Workspace and Inspector do not accept drops anymore.
The morph menu allows to accept/not accept drops for a whole hierarchy of morphs.
We briefly discussed a better solution to block drops in all dev-tools and e.g. color-pickers as well. Since we did not come up with a good solution we opted for this, since these tools were the biggest pain points for us.
This closes #56

#56 no drops in dev-tools and option in morphic properties menu

---

lively.components/prompts.js

This is just a tiny quality-of-life change. Some of the prompt-types already had a static example function that utilized the wrappers in `world`. I added the remaining ones.

prompts: add static example method for all prompts

---

lively.lang/package.json
lively.lang/string.js
lively.morphic/morph.js

See #160 for context.
Since the linter has not yet run on strings.js a lot of additional style changes were added in this commit. The changes I wanted to cause:
- Add articles dependency
- Add findArticle and articlize for strings.js (See line 121 following)
- Use findArticle to use the correct article on default name in morph

Use correct article for default name

---

lively.morphic/undo.js

We needed this to accomplish correct undo behavior in a more complex scenario.
Short story is that we check *after* an action was completed if this was an allowed action and revert it manually if this was not the case. This nevertheless created an corresponding undo, since the beginning of the process is the same with legal actions. Therefore we wanted to remove these.
We see that this method needs to be used with care and are open to discuss alternatives/give a more in-depth explanation of what happens in our application if you have strong concerns about this.

Add a method so the latest element on the undo stack can be deleted

---

lively.morphic/events/Keys.js

There was a bug, where an error message got saved in the `event.keyCombo` because the `key` was `undefined`.

Add check if key is defined and remove unnecessary cases

---

lively.morphic/text/search.js

- clicking in the text will leave the cursor where it is and not reset the position
- if the old (reset) behavior is wanted, the cancel button is present
- navigate the search results with enter and alt-enter (normally it would be shift-enter, but that is bound to delete the word before the cursor....)
- pressing enter will also write the input to the search history
- escape will leave the cursor where it is and close the search
There are more things that would be nice regarding the search widget, but these are the ones with "bang for the buck", at least for us :wink:

Nicer Searching

---

lively.morphic/events/KeyHandler.js

Closes #59 
In the original Issue the scope was maybe larger, but these were the worst offenders from my point of view.
The Shift, Enter,... symbols are on most reasonable keyboards, the three symbols I touched are platform specific.
I am absolutely open to change the Windows one, maybe just writing meta is better.

Prettier Keycombos

---

lively.morphic/morph.js

Just a small signal in order to do clean up somewhere else before the morph is abandoned since at the beginning of the method the morph is still there. We need this in order to clean up editor elements when a Morph that is part of the currently open Interactive gets removed via its Halos.

morph: signal onAbandon at the beginning of abandon

---

lively.freezer/index.js

Otherwise the comment browser may be frozen as well.

freezer: add lively.collab to exclusion list

---

lively.ide/value-widgets.js

We have NumberWidgets which we fill with floating point numbers but don't want to have displayed in a rounded fashion. This is why we set floatingPoint to false. This however did not do anything, because when floatingPoint is set to false, it ignores the property, and derives its value.
With this change, floatingPoint is only derived, if floatingPoint has not been explicitly set.

number widgets: return floatingPoint when it has been explicitly set

---

lively.ast/lib/code-categorizer.js
lively.ide/js/browser/index.js

Closes #210 
getters for properties and commands as well as array declarations are now expandable in the browser.
Tests could be another useful addition, they provide no declarations at all in the browser right now, but I am not able to tackle that right now. I wrote it down however. 
---
I handled one case for ...generateUnfolded in Morph explicitly, I do not know if there are many more like it?  (@merryman?)

Expanding properties/commands in JS browser

---

README.md

This is an open PR mainly as a public service announcement:
We have migrated the bulk of our internal wiki over into the wiki of this repositorie. Some smaller things might follow after internal revision, but this is nearly everything.
It is worth noting that some of these pages were created more as minutes from our discussions with @merryman than that they were directly intended as public documentation.
On the other side, some articles are of really high quality like the one @SilvanVerhoeven wrote about connections (at least in my opinion :slightly_smiling_face:).
However, this might be a good starting point. We will add to this wiki as of now when appropriate.

Add link to project wiki in README

---

lively.halos/morph.js
lively.ide/js/inspector.js

Closes #288
The change in the inspector is necessary, otherwise clicking the target selector button and then releasing the mouse selects the target inspector button requiring one to keep the mouse pressed for the duration of the selection.

inspector: select morphs via mouse up

---

lively.ide/value-widgets.js

Is there a reason we first set the value of the number widget and only after that set the unit? because the value scrubber won't be able to display the unit then in the first round of relayouting
closes #295

Fix number widget relayout after setting unit

---

lively.freezer/index.js

Closes #300 
The `needsClassInstrumentation` method was called elsewhere with only one parameter `id`. This lead to source being undefined and therefore no method `match` being found. Checking for undefined fixed the problem for me. I tested it with one of our interactives as well as a basic rect morph.

freezer: check for undefined before matching string

---

lively.ide/world.js
lively.morphic/morph.js
lively.morphic/text/label.js

Also preselects the already input text when changing the content of a label or the image URL over the morph menu.
This was feedback from the user testing on Friday, that it is cumbersome to change those values.

prompt: add option to select input upon opening

---

lively.ide/studio/top-bar.js

For all morphs that are submorphs of a morph (inclusive) that has `showHalosForContent` set to `true`, halos can be triggered in Halo mode via a normal click, even if they are in a window.

topbar: allow halos in (parts of) windows

---

lively.components/widgets.js

By handling what normally `openWorldMenu` of the IDE would do, it is possible to bundle DropDownSelector widgets without bundling in the whole IDE package.

widgets: let dropdown handle its own menu creation

---

lively.ide/test-runner.js

This adjusts the html code of the test runner, such that it reacts to `mousedown` events instead of `mouseup`.
`mouseup` led to several situations where one would accidentally trigger a error diff etc without intention.

🧰: test runner reacts to mouse down

---

Dockerfile
Makefile
README.md
install.sh
lively.headless/index.js

This has the following benefits:
- It is not longer necessary to have node / other dependencies installed (although docker is needed)
- Should run on Windows without headaches.
Any changes made to source code in the running lively instance are visible in the file-system as usual, so the usual workflows are unaffected.
Running on windows is still slightly annoying/requires the same amount of work as without docker, since docker needs either WSL or HyperV on Windows and usage of lively.next would be equally possible with just WSL.
**I still propose to merge this, for the following reasons:**
1. It allows us to get a "source of truth" environment that can be used to make sure that no environment mess-ups of personal configs are the source of weird behavior when investigating/reporting bugs …

Add support for running lively in a docker container

---

lively.ide/text/code-evaluation-commands.js

Logically, specifying `--porcelain` does not provide the porcelain output, but the one intended for plumbing.
This is now fixed, providing sensible output when blaming multiple lines.

🧰: Improve output of the `blame selection` command to be human readable

---

lively.graphics/color.js

Using black there lead to the ColorPicker being in the lower left corner when opening it, which lead to the hue being lost in the internal representation which uses RGB.
Thus, changing the hue in the ColorPicker UI had no observable effect.
Color transparent now uses some kind of blue with a transparent alpha.
This video shows that imo, color animations still work as intended
https://user-images.githubusercontent.com/14252419/176926010-5433d82c-8d99-42a4-9e53-2e8978175d36.mp4
.

🖌️: Don't use black for Color.transparent

---

lively.ide/studio/controls/fill.cp.js

Previously, when selecting a morph with opened property panel, opening the color picker for fill, closing it and then deleting the morph with its remove halo, an error occured.
This change fixes that.
The removed call changed the fill of the ColorPicker view, which caused more causes via connections. Those were problematic, since the propertie panel was already being cleaned up since the previous target morph was to be deleted.

🧰: Fix failing combination of delete halo and color picker usage

---

Dockerfile
README.md

This fixes the `spellcheck word` command of Text.

🐳: Add `aspell` to installed deps in container and README

---

lively.ide/js/mode.js
lively.ide/themes/dark.js
lively.ide/themes/default.js

This solution is improved over the older variant that we had and is taken from here: https://discuss.codemirror.net/t/highlighting-fixme/171/3.
When we update mode.js from a newer CodeMirror version, we need to think of this and reconcile this part manually.

🧰: Reenable highlighting of TODO and FIXME comments

---

scripts/check-build-status.py

We need to install lively before checking if the artifact might be unchanged despite file changes, since otherwise the build of the artifact will fail due to missing dependencies. I only tested it locally and there it worked ofc. 
I am a bit unsure if this is a problematic solution, since we depend on the installer here. However, we only run into this case, if the installer has not been modified. This means, that the previous installer version which was commited will be used, and due to our checks is working.
If the premise, that the installer was not modified does not hold, we might fail, but in that case a red check is what we would want anyways.
Thus, I think this is OK but just wanted to check with you...

🛠️: Install lively before trying to rebuild artifact

---

.github/workflows/check_world_loading.yml
scripts/check_boot.js

This action would currently run upon **pull request approval**.
I chose that since it is a) guaranteed to happen with our current setup and b) should happen exactly **once** (at least currently).
Because this action needs to install lively again (and I do not see a good way of sharing this installation between our different actions atm) it takes a while and burns resources. I decided this should not happen more often than necessary (think of the :polar_bear:)

🛠️: Add CI check that lively loads successfully in browser

---

lively.halos/morph.js
lively.ide/world.js

Fixes an issue when copy and pasting a morph via clipboard.

🧰: fix copy and paste of morph

---

scripts/check-build-status.py

The problem occurred due to the way we invoked `git rev-list` previously. With just one argument, that can either be a revision or a filename. With no-longer-existing files, git assumes it is a revision, does not find that neither and crashes. `--` separates revisions and filenames and now we are fine, even when files got deleted.

Robust artifact checker

---

lively.ide/studio/version-checker.cp.js

Now uses
- green checkmark to indicate that we are even
- red arrow down in case one is locally behind
- red arrow up and down in case there are unique commits on remote and locally (diverged)
- blue arrow up in case one is ahead of remote
- read triangle in case there was an error executing the git commands to check the status
We do not use the GitHub API anymore, but instead use a git command. We always compare the currently checked out commit (HEAD) with origin/main.

Improved version checker

---

lively.user/server/server.js

Prevents the lively server from crashing when running the `lively.user` tests.

👤: prevent server from crashing on test run

---

.github/workflows/check_docs.yml
.github/workflows/check_world_loading.yml

As main is protected, and our check actions run on pull requests, running them again after merging does not provide added benefit.

🛠️: do not run check actions on commits on main

---

lively.ide/test-runner.js
lively.server/plugins/test-runner.js

The test runner now properly channels through the error message in case an error is thrown during the test execution.

👔🧰: fix test runner error handling in subserver

---

lively.morphic/rendering/animations.js

This fixes a missing import inside `animations.js` that made animations not work on polygon/path morphs.

🎨: fix missing addSvgAttributes import in animations

---

lively.ide/js/browser/ui.cp.js

Adds some tooltips to the navigation buttons in the System Browser. Also makes sure the freeze button is only visible in `.js` files.

🧰: fix tooltips and button visibility in system browser

---

lively.components/window.js
lively.ide/world.js

Fixes an issue where windows would overlap the visible window bounds when opened, making certain parts of the window controls inaccessible.

🧰🎛️: fix window fitting to world bounds on openInWindow()

---

lively.morphic/components/core.js
lively.morphic/components/policy.js
lively.morphic/helpers.js
lively.morphic/tests/components-test.cp.js
lively.morphic/text/morph.js

StylePolicies were still not able to properly handle embedded morphs within the `textAndAttributes`. This PR will extend the style management to those morphs as well.

🎨: fix embedding of morphs in textAndAttributes of component defs

---

lively.ide/world.js

Fixes an issue where saving a world with open sidebars would prevent the reloaded world from opening those sidebars again.

🧰: exclude activeSidebars form serialization

---

lively.morphic/tooltips.js

Fixes an issue where tooltip would overlap the world bounds.

🎨: prevent tooltips from overlapping world bounds

---

lively.morphic/components/policy.js
lively.morphic/morph.js
lively.morphic/tests/components-test.cp.js

Fixes an issue reported by https://github.com/engageLively/galyleo-dashboard/issues/95.
Concretely, when assigning new masters to various morphs in a nested submorph hierarchy,
the enclosing masters can end up overriding the newly assigned masters, leading to
unexpected behavior.

🎨: fix nested components overriding each other

---

lively.ide/js/browser/index.js

Fixes an issue with the browser that happened on my machine, where opening a search result from the code search would not scroll and highlight the correct line in the module source.

🧰: ensure browser scrolls to cursor pos if not explicit scroll specified

---

lively.ide/js/browser/index.js

Previously, it was possible to a) navigate inside of the browser columns while one would have wanted to navigate in the list of the fader and b) the focus was quite often not in the search bar in the fader.

🧰: disable keyboard navigation in browser columns on window fader

---

lively.morphic/tooltips.js

Fixes an issue that places the tooltips incorrectly once the world is scrolled.

🎨: fix position of tooltips on scrolled world

---

lively.ide/test-runner.js

When opening a test from the test runner that is already opened in a browser in the world, that browser was previously not uncollapsed if its window was minimized.

🧰: maximize collapsed browser when opening test

---

lively.components/list.js

A small adjustment to #524. Dropdowns that are part of a popup now also need to install the Popup style class on the lists since those are opened in the world as well. If that is not done, the Popup overlaps the lists, making them inaccessible (see the color picker for instance).

🎛️: attach Popup style classes to lists open in world

---

lively.lang/array.js
lively.lang/object.js
lively.lang/tests/object-test.js

Closes #549.
Unfortunately, the linter came with a Klappstuhl in array.js. All those changes are in a separate commit however, so that it should be alright if you take a look at the changes commit-wise and not all at once :)

Object Equals for circular objects

---

lively.components/widgets.js

Fixes a problem that I overlooked previously in #526 where the base value would not be adjusted after a scrub-drag was fully performed. So that would lead to the scrubber to always start from the very initial value, instead of starting the next scrub from the recently adjusted value.

🎛️: align scrubbed value on drag end

---

lively.components/canvas.js
lively.ide/text/map.js

This PR fixes some small annoyances that became apparent with the option to enable the `TextMap` all the time, which lead to a `Canvas` element it being open way more often.
The `willReadFrequently` option is an optimization that Chrome suggested in the console :grin:.
All in all, this should stop the endless stream of warnings/errors when having a `Console` as well as a `TextMap` open.

Fix problems with Canvas

---

lively.morphic/components/core.js

This is an interesting problem that I ran into. I am very positive that we need to find a nice solution to the underlying problem - if this solution is, it I am not so sure about. Thus, this is a RFC as well as a PR :D
**What is the underlying problem to solve**: 
Generally, one great thing about component systems where view and behavior are separated (besides all the non-coder boogaloo :slightly_smiling_face:) is that they allow for great reuse of code, especially on the model side, i.e., I can build several different front ends that serve similar purposes in different contexts and just attach the same model.
Concretely, I stumbled upon this problem when building a kind of "rich text formatting halo", that should provide a subset of the functionality of the text controls currently …

🎨: do not fail when binding target is removed from component

---

lively.components/menus.js
lively.ide/js/inspector/context.js
lively.ide/js/inspector/index.js

This resolves some minor UX problems that occured presumably since we switched to the new PopUp Widgets.
Namely, now:
- only one widget can be open at any time,
- scrolling or switching the inspectors target will close any open widgets,
- closing the window of the inspector will close any open widgets.

Fix inspector widgets

---

lively.ide/debug/console.cp.js
lively.morphic/helpers.js

This is a small correction to #554 which adjusts the default extent of the console and removes a debugger statement.

🧰: adjust default extent of console

---

lively.components/list.js

🎛️: fix typo in `list.js`

---

lively.modules/src/import-export.js

Fixes an issue where a module would not propagate its changes when its entities are exported via export lists.

🧩: fix propagation of changed export lists

---

lively.morphic/text/morph.js

Fixes an issue where we could set the scroll of a text morph beyond the possible scroll dictated by the bounds of the document.

🎨: prevent setting text scroll ahead of document bounds

---

lively.morphic/rendering/font-metric.js

Revision to #602. There was a bug where we would accidentally loose embedded line morphs since they were being rendered into an intermediate line that was not mounted back.

🎨: fix lost embedded submorphs issue when measuring line

---

lively.ide/js/inspector/context.js

Fixes empty inspectors when inspecting certain data structures.
It happens when some of the values inside a structure that are supposed to be displayed in the inspector fail to convert to a string. I replaced the printing approach in the inspector with a `safePrint` that attempts different stringification attempts and wraps each in a try/catch.
closes #610.

🧰: avoid empty inspector when printing of values fails

---

lively.morphic/morph.js

Fixes an issue where adding a morph via `addMorphAt` would not properly set the structural changes flag, leading to missing morphs in the rendered scene.

🎨: fix setting of structuralChanges flag when morph added

---

lively.components/canvas.js

In certain scenarios, the canvas context is unable to generate a data url. Those cases used to cause crashes in the initialisation of canvas morphs. We now fail silently and return an empty string instead.

🎛️: catch error when data url generation fails

---

lively.ide/studio/controls/popups.cp.js
lively.ide/studio/shared.cp.js

Implements proper button styling for dark and light padding controls:

🧰: properly style dark and light padding controls

---

install.sh
lively.installer/install.js

Fixes an issue that happens on systems where the architecture demands to build leveldown on the machine.
We temporary create a symlink that can then be used by any build script invoking `node-gyp`. The symlink is then deleted.

📦: ensure node-gyp when building lively packages

---

lively.ide/value-widgets.js

Co-authored-by: Rick McGeer <rickmcgeer@users.noreply.github.com>"
Closes #588.

🧰: respect min and max values when scrubbing in number widgets

---

lively.ide/studio/controls/border.cp.js
lively.ide/styling/color-picker.cp.js

Correction to #639 where the border popup would not display the controls correctly.

🧰: fix layout of border popup

---

lively.morphic/world-loading.js
lively.morphic/world.js

Fixes an issue with incorrect invocation of the world loading when using resources.

🎨: pass module manager when loading world via file path

---

lively.morphic/text/morph.js

Fixes the well known issue of negative overscroll in text morphs.

🎨: prevent negative scroll in text morph

---

lively.halos/morph.js
lively.ide/js/inspector/index.js

Fixes the check if an Inspector for a given Object is already opened and if so, retrieves that.

🧰👼: fix prevention of multiple inspectors for the same object

---

lively.components/window.js
lively.graphics/geometry-2d.js
lively.ide/js/linter.js
lively.ide/world-commands.js
lively.ide/world.js
lively.morphic/rendering/property-dom-mapping.js

Closes #620.
Also fixes a problem where windows would change their position/bounds when being minimized/uncollapsed.
Resizing windows with the left and top resizers will no longer result in changed positions or bounds.
Maximizing windows will now behave smarter. When a window is maximized (double click on the window title) and is currently not displayed in fullscreen, it will go into fullscreen. Double clicking a window that is displayed in full screen will change its position and extent back to the last values **before** the window was displayed in fullscreen.

Various Window Fixes

---

lively.morphic/text/morph.js

Closes #627.
When going through the list of commands that are available on `Text`, it turned out, that they all only really make sense when one has an editable morph at ones hand. We briefly thought about extracting the commands into an EditorPlugin or the base EditorPlugin, but since the whole editing of `Text` is implemented via commands, and we have things like the world naming input line which require editing but do not have any plugin, and we did not want to have an IDE dependency to a new plugin in the text morph, we opted for this solution.

🎨: only add text specific commands for interactive texts

---

lively.morphic/env.js
lively.morphic/rendering/renderer.js
lively.morphic/text/morph.js

Fixes an issue, where creating an input line would cause a crash of the renderer like so: `part(InputLineDefault, { readOnly: true, needsDocument: false }).openInWorld();`

🎨: avoid incorrect scroll layer adjustment request in text morphs

---

lively.source-transform/index.js

Fixes another issue related to #678. Transpilation in lively.next is pretty much all over the place now, but I wont get to that until I will have a chance to revisit the SystemJS6 upgrade project is underway. In the meantime this will squash the errors.

🔁: replace outdated rest-spread plugin, add optional-chaining transpile

---

install.sh

Currently, node 19 doesn't install.

Add check for node 19

---

lively-system-interface/interfaces/local-system.js
lively.ide/js/browser/index.js

Ignored packages as defined in the package json where no longer properly adhered by the system interface.
This lead to performance issues when browsing packages with huge ignored directories (i.e. lively.freezer).

🧰📠: properly take into account the ignored files defined in package.json

---

lively.morphic/text/morph.js

Previously, it was possible that `patchSpecialProps` was executed before the scrollLayer and scrollWrapper were initialized and thus the renderer would silently fail.

🎨: fix initializing of text with hidden scrollbars

---

lively.morphic/components/core.js

Fixes an issue where `ensureFont()` would just terminate without loading the font if invoked before `$world` was initialized. (happens quite a bit in bundles).

🎨: wait for $world on ensureFont()

---

lively.ide/world.js

Fixes a minor issue, where halos that were focusing on nested morphs were not getting realigned if the world was scrolled.

🧰: update halos with deep targets on world scroll

---

lively.morphic/components/core.js
lively.morphic/components/policy.js
lively.morphic/tests/components-test.cp.js

Fixes issues that arose with component definitions that contained specs without a name property.
This fix will either carry over the name of the master component for that *anonymous* spec, or generate a UUID that will server as the default name, if needed.

🎨: ensure non conflicting default names for morphs in policies

---

lively.components/loading-indicator.cp.js
lively.ide/test-runner.js

In order to know if the test runner is *currently* executing tests, we now display a loading indicator that indicates that currently tests are being run.

🧰🎛️: display loading indicator on running tests in runner

---

lively.ide/world.js

In order to prevent the initial long wait when invoking the import completion for the first time, we move that module export computation into the load of the world itself.

🧰: precompute module exports on world load

---

lively.freezer/src/loading-screen.cp.js

❄️: ensure to trigger loading indicator after loading screen is mounted

---

Makefile

This caused the docker action we recently introduced to fail all the time, just because it ran inside of Github Actions.

🐳: fix docker-setup when running outside of a TTY

---

lively.components/muller-columns.cp.js

Fixes a common issue where muller columns inside the system browser would steal the focus when hovered, while a text morph was still holding onto the focus in order to receive text input. I believe this is one of the main causes for unfocused filtered list prompts.
Should fix some of #668

🎛️: stop muller columns from stealing active text focus

---

scripts/test.js

This solves a problem that should never have occurred, I somehow missed these.
This should solve empty output in the summary of our CI run, like these:

🛠️: fix summary output of tests in CI

---

lively.ide/studio/top-bar.cp.js
lively.morphic/config.js

Closes #736, as requested by @rickmcgeer.
Note, that this is an optional feature, that is disabled by default. To enable it, you need to add `config.ide.studio.worldMenuInTopBar = true` in your `localconfig.js` at the root of your lively.next folder.

🧰🎨: add option to trigger world menu via top bar

---

lively.morphic/helpers.js

Glancing over #739, I discovered that the reset mechanism for the style properties cache itself never really worked. This fixes that.

🎨: fix style property cache reset mechanism

---

lively.ide/studio/dark-color-picker.cp.js
lively.ide/studio/version-checker.cp.js
lively.ide/styling/color-picker.cp.js
lively.ide/styling/color-picker.js
lively.morphic/rendering/animations.js
lively.morphic/rendering/renderer.js

Adds a button to copy the currently running commit of lively.next from the color picker as well as the option to copy the currently picked color from the color picker.
https://user-images.githubusercontent.com/14252419/224113523-f6a39926-f006-4b8d-8ace-66b05307b268.mp4
---
In order to get the color effect on the copy button, I implemented the possibility to animate css properties which are applied to the textlayer of a text morph.

Add Copy Button to Color Picker and Version Checker

---

.github/workflows/check_world_loading.yml

This fixes a problem that occurred since last Friday, when the 'Check if lively boots' action began failing all of a sudden. The error occurred when the loading screen got bundled during the installation. The problem only occurred in this action.
This is the stack trace of the failing:
```
Setting env vars for FLATN_PACKAGE_DIRS, FLATN_PACKAGE_COLLECTION_DIRS, FLATN_DEV_PACKAGE_DIRS for lively.next
[lively.freezer]: Freezing in Progress
/home/runner/work/lively.next/lively.next/lively.next-node_modules/@rollup__SLASH__plugin-commonjs/22.0.0/dist/cjs/index.js:184
for (const path$1 of glob__default["default"].sync(isNegated ? pattern.substr(1) : pattern)) {
^
TypeError: glob__default.default.sync is not a function or its return value is not iterable
at getDynamicRequireModules …
```

🛠️: pin puppeteer version used inside of action

---

lively.ide/js/browser/ui.cp.js
lively.ide/js/inspector/ui.cp.js
lively.morphic/text/morph.js

We did not understand the problem 100 percent, but this is what we gathered:
When a morph gets instantiated from an inline-component, the following happens: 
1. The structure gets created.
2. Non-style properties get set.
3. Specified style-properties get set.
The `readOnly` property of `Text` was a  style property previously (for unknown reasons). Thus, it was set to `true` for the longest time during the instantiation of the editor and only later set to false. This broke with assumptions I made when implementing the text rendering and the text implementation. Thus, an alternative fix for this would have been setting `needsDocument` to true on the source editor of the inspector.
However, this goes against how the `needsDocument` flag is used, at its purpose is to enforce a document on …

Fix Editor in Inspector

---

lively.morphic/rendering/font-metric.js

Fixes an issue where the patching of the fixed morphs would break, leaving nodes behind in the DOM that would keep sticking around although the morphs were not longer in the world. Closes #764 and #734.

🎨: properly install dom measure at the beginning of the document body

---

lively.morphic/rendering/property-dom-mapping.js

Fixes an issue where transitioning from a opaque fill to a gradient fill with a transparent stop, the transparent stop would not be visible.

🎨: fix rendering of gradient with transparency

---

lively.ide/studio/shared.cp.js

I changed the CSS class name for better readability (imo) but forgot to change the animation as well. Thus, the spinner did not spin. This is now fixed.

🧰: fix spinner loading animation

---

lively.freezer/tools/build-loading-screen.sh

For whatever reason, we were still missing the `no-experimental-fetch` flag in the loading screen build script. This *may* have also caused the issues reported in #731 which to date still keep popping up.

❄️: add no experimental fetch flag to loading screen build script

---

lively.halos/morph.js

For elements that are direct descendents of $world, the scaling property is basically disabled, as their scaling gets dictated by the zoom of the world. However this is a) only correct when the zoom behavior in the world is enabled and b) in that case the halo should also never display the scale icon.

Fix behaviour of scaling/rotation halo

---

lively.morphic/morph.js
lively.morphic/rendering/renderer.js

Previously, we handled this by utilizing morphic styleClasses, which led to problems in conjunction with components, see https://github.com/LivelyKernel/lively.next/issues/796

🎨: handle hiding of scrollbars directly in renderer

---

lively.graphics/geometry-2d.js
lively.ide/studio/top-bar.cp.js

Previously, we could only create shapes with the top-bar tooling from by dragging from the top-left to the bottom-right of the shape to be created. However, we could create grey selections in the other direction as well.
This PR reuses the strategy from selections for the other shapes in order to allow easier creation of shapes.

🧰🖌️: allow drag-creation of morphs not only from top-left

---

lively.ide/studio/dialogs.cp.js

The `ConstraintLayout` is currently totally JS-based (see #625) and quite quirky. Since I'd like to remix the `SaveWorldDialog` for the saving of Projects, I got rid of the `ConstraintLayout` and replaced it with `TilingLayout`s and a few wrapper morphs.

🧰: restructure save world dialogue to use `TilingLayout`, not constraint

---

lively.ide/studio/top-bar.cp.js
lively.morphic/rendering/renderer.js
lively.morphic/text/morph.js

Since the Cursor Color is a separate property, the cursor was often very hard to see, especially on dark backgrounds. This PR allows to enable adaptive coloring of the cursor, so that the cursor always assumes the color of the character at the current cursor position. The option of hardcoding the cursor color does still exist. Per default, the adaptive cursor coloring is active for text morphs that are created with the topbar and inactive for all other text morphs.
https://user-images.githubusercontent.com/14252419/235676785-eb9a1a9e-7964-44c1-aaef-8644f60f683a.mp4

🎨🧰: add option for adaptive cursor coloring

---

lively.morphic/layout.js

Fixes an issue with CSS layouts, where an optimization would cause morphs to be incorrectly updated based on the DOM state, if there had pending structural changes that *where not yet updated in the DOM*.

🎨: prevent premature layout measuring with pending structural changes

---

lively.morphic/components/core.js
lively.morphic/morph.js

Allows us to *finally* define dynamic bindings that (potentially) match multiple morphs and also are updated whenever the view changes.

🎨: implement match based bindings

---

lively.morphic/components/policy.js

Adds a missing line to #839 that somehow was not included in the PR but is essential for making things work. Closes #844.

🎨: fix getSubSpecAt() call policy.__serialize__() expressions

---

README.md
install.sh

The problem was that the CI variable is "overloaded" in the sense that we use it to skip minification locally and skip entire build steps remotely.
The advanced condition will now build the landing page in the docker container as well, while not minifying the code (at least for the loading-screen, skipping the minification in the landing page is in #684.

🛠️🗒️: build landing page in docker container and advise against docker

---

lively.components/prompts.cp.js
lively.ide/studio/version-checker.cp.js
lively.project/project.js

This intends to make it easier to work with feature branches in combination with projects while developing the core of lively.next. Previously, we would bind projects against the currently checked out commit. When developing on a feature branch, especially when using `git rebase`, this often lead to situations where projects would not open anymore due to incompatible versions.
We now only bind against commits on `main`.
The check for a compatible version also checks the relationship between the latest commit that is shared with `main` and the currently checked out branch and the version specified in the `package.json` of the project.
The following scenarios are possible:
1. Both are the same and we are good to go.
2. The latest shared commit is newer than the previous commit from `main` …

📂🧰: only bind and check projects against (shared) commits on main

---

lively.morphic/morph.js

Throws a comprehensive exception if we are requesting the natural extent of an image morph before this is computed.

🎨: throw error when requesting naturalExtent although not yet determined

---

lively.morphic/morph.js

In response to #881 and further avoiding scenarios where we break the renderer by introducing incorrect properties.
This will block incorrect values for `origin`, `position`, `extent`, `scale` and `rotation` from entering the morphic state and corrupting the scene graph/renderer.

🎨: prevent intrusion of invalid transform related properties

---

lively.ide/studio/version-checker.cp.js

The Version Checker did not call git fetch previously, which lead to comparisons with outdated branch statuses, if one did not performed a manual fetch.

🧰: fetch current remote before checking if lively is up to date

---

README.md

We recently discovered that not having setup SSH access with `git` and GitHub, as well as a `git` version below `2.28` will crash the creation/opening of projects. The version requirement stems from `git init -b`.
This PR mentions these requirements in the README.

🗒️: add requirements for project feature to `README`

---

lively.collab/comments/comment-browser.js
lively.ide/studio/top-bar-buttons.cp.js
lively.ide/studio/top-bar.cp.js

The top bar component definition included a bunch of button parts, that did not have their name directly declared. This currently does not bode well with our component tooling, and I would suggests for the time being to keep the names around,  even though it is sort of "redundant" in this case.

🧰: ensure names present for buttons in top bar def

---

lively.ide/js/linter.js

Variables that contained a underscore matched the provided pattern and thus did not trigger a warning when they were imported/defined without being used.
I suspect that we just copied that from somewhere and had no special thoughts when originally setting this rule. :woman_shrugging:

🧰: don't exclude vars with underscore in name from `no-unused-vars` rule

---

lively.shell/server-command.js

Closes #897.
From the `nodeJS` docs:
> Use cwd to specify the working directory from which the process is spawned. If not given, the default is to inherit the current working directory. If given, but the path does not exist, the child process emits an ENOENT error and exits immediately. ENOENT is also emitted when the command does not exist.
For not entirely clear reasons, the now removed `reject()` call crashed the server and we were unable to fix that neither with `try/catch` nor with `Promise.catch()`.

🐚: stop `ENOENT` from non-existing `cwd` from killing the server

---

lively.morphic/rendering/renderer.js

Fixes a bug where upon the first time of entering the "edit mode" of a text morph the scroll layer would show scroll bars no matter what the scroll mode of the text actually was.

🎨: fix scroll layer initialization

---

lively.morphic/layout.js
lively.morphic/rendering/morphic-default.js
lively.morphic/rendering/property-dom-mapping.js
lively.morphic/rendering/renderer.js

Inconsistent mixing of dashed and camel case notation of css style prop names inside the renderer, would cause the render update logic to have difficulty clearing old, unused props for the DOM.

🎨: fix style prop patching of dom nodes

---

lively.morphic/rendering/renderer.js

Fixes issues with rendering fixed morphs in the presence of external scripts (i.e. Google Charts) injecting random stuff into the body.

🎨: cleanup fixed morph node after renderer stopped

---

lively.morphic/rendering/property-dom-mapping.js

We rounded too aggressively, leading to visible stutters when animating rotation.

🎨: improve precision of rendered rotation in morphs

---

lively.morphic/tests/rendering-tests.js
lively.morphic/text/morph.js

This is a revision of the previous fix to the style property patching: #916. We forgot to adjust some of the style props being set inside the text morph implementation.

🚨 Correction to fixed style prop patching

---

lively.project/project.js

Instead of failing hard upon loading a project with missing dot files (workflow/buildscript) we instead create the missing files.

📂: create missing dotfiles on loading projects

---

lively.ide/debug/console.cp.js
lively.morphic/components/core.js

Fixes a fatal crash in the log console that is caused by a new implementation of the view model we recently merged #900.

🎨🧰: prevent infinite loops on console menu/command getters

---

lively.ide/js/browser/index.js

See https://www.git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#_formatting_and_whitespace for more information.
The git conversion kicks in only when a file is actually committed. Therefore, I also enforced the line ending on system browser level. Doing this, is think I also discovered a bug in `updateSource`, which would never actually apply the source cleanups? 
Closes #187.

🛠️🧰: enforce `LF` line-endings in repository and system browser

---

lively.morphic/morph.js
lively.morphic/rendering/renderer.js

Fixes a rendering issue, where adjusting the origin would not update the submorph wrapper node.

🎨: update submorph wrapper node on origin adjustment

---

lively.morphic/components/policy.js

Fixes an issue that was introduced in #856 where parts without a name property would create morphs with the name being `undefined` causing crashes.

🎨: do not inherit name from parent spec if undefined

---

lively.morphic/layout.js

This reverts commit d422b5021c5c86f95b97f9956579458976a354c4.
We could not reconstruct the reason as to why this change was made exactly. However, it lead to situations in which Popups had their layouts applied with wrong settings. With a quick glance, we could not find any morphs breaking reversing this.

Revert "🎨: fix layout hugging getter"

---

lively.ide/studio/controls/body.cp.js
lively.ide/studio/controls/border.cp.js
lively.ide/studio/controls/layout.cp.js
lively.ide/studio/controls/text.cp.js
lively.ide/studio/properties-panel.cp.js

Previously copy-pasting a morph would lead to side bar view models being retained via dangling connections on the new instance, causing errors.

🧰: ensure side bar connections are not being serialized on copy

---

lively.halos/morph.js

Closes #936.
Why the solution actually works, remains unclear to me.
It appears to be fixed by inserting the scale of the target into the offset rectangles we use to compute the new bounds for the morphs.

👼: correctly factor in target scale when updating bounds

---

lively.ide/studio/world-browser.cp.js

🧰: fix `ProjectIcon` after renaming `tabler-icons` font `Tabler Icons`

---

.github/workflows/build_docs.yml
.github/workflows/check_builds.yml
.github/workflows/check_docs_build.yml
.github/workflows/check_docs_coverage.yml
.github/workflows/check_world_loading.yml
.github/workflows/ci-tests.yml
.github/workflows/pr_labeler.yml
lively.project/templates/test-action.js

There is a new beta feature on GitHub allowing to deploy from within Actions, without the need to push to a branch.
I discovered this working on auto-deployment of Projects, as think this is preferable for the documentation as well.
The current deployment of https://livelykernel.github.io/lively.next/ has been triggered with this action. :slightly_smiling_face:

Deploy Documentation from GitHub Action

---

scripts/test.js
scripts/test.sh

GitHub does not render Emojis consistently. What happens is that GitHub runs a detection for emojis, and renders them as some special HTML, fetching their images and stuff. However, this detection is somewhat flaky. This caused inconsistent output in our "Run Tests" pipeline. I also reported that [here](https://github.com/orgs/community/discussions/62382).
I found a fix for this, as we do not need super many emojis for the test summary: I just replace all affected characters with the HTML GitHub *should* generate anyways.
See https://github.com/LivelyKernel/lively.next/actions/runs/5796307806 for a demonstration of the change working.

🛠️: enforce consistent emoji output with GitHubs markdown renderer

---

lively.components/inputs.js

The browser styling stems from the User Agent Stylesheet.
We need to check this whenever we utilize native input elements. Currently, the only other occurrence of this I could find is the `PasswordInputLine`, but that works fine for me.
Closes #989.

🎛️: take browser styling into account for size of `CheckBoxMorph`

---

lively.freezer/src/loading-screen.cp.js
lively.freezer/src/ui.cp.js

This should resolve this error
that occurred during the loading-screen. Only the default CSS string values are valid ('normal', 'bold') and numbers as Strings (we convert them internally).

❄️: fix invalid `fontWeight` values leading to error on load attempt

---

README.md
lively.freezer/package.json
lively.freezer/tools/build.landing-page.mjs
lively.freezer/tools/build.loading-screen.mjs
scripts/node_version_checker.sh

Minor fix to the json-plugin in rollup, that allows us to now support any node version > 18.

Support node.js > 18

---

install.sh
lively.ide/studio/component-browser.cp.js
lively.ide/world-commands.js
lively.ide/world.js

This makes it so that we clone/update the official partsbin during `install.sh` and automatically load it when opening the components browser. Thus, the partsbin can move more in the direction of its original idea, being a "wundertüte" to be used easily by all lively.next users.

`partsbin` integration

---

lively.ide/studio/world-browser.cp.js

The "Warning" was previously just not shown. To make matters worse, that did not stop it from catching the cursor, making it impossible to open some project after one searched for a term without any results. 
Both of these should now be resolved.

🧰: fix warning not appearing and additionally blocking clicks

---

lively.components/prompts.cp.js
lively.project/prompts.cp.js

Previously, it could happen that once accidentally clicked the OK buttons on the project creation/save form multiple times, which in most cases lead to problematic situations when we triggered some operations on disk in parallel.
Now, we stop that from happening by internally blocking the resolve method via a flag and additionally stopping the user from pressing the OK button multiple times as long as we block.

📂🎛️: stop project related prompt from being resolved multiple times

---

lively.components/widgets/mode-selector.cp.js
lively.ide/studio/dialogs.cp.js
lively.project/project.js
lively.project/prompts.cp.js
lively.shell/git-client-resource.js

With this PR, we properly support the creation of projects whose github repositories are private.
When creating a Project, one can choose to create a private repository. This option is only available when a repository gets created:
When a private repository is created, we do not create the deployment action, since github pages is not available for non-paying users on private repositories. We make an exception from this rule if the owner of the repository is logged in and on a payed github plan. This is not a perfect solution, since collaborators on a free plan would also benefit from the repo belonging to a paying user.
We also allow changing the visibility of a project inside of the project settings. Doing so allows/disallows the addition of the deployment action.
The change gets …

Private Projects

---

lively.ide/studio/top-bar.cp.js
lively.project/project.js
lively.project/prompts.cp.js
lively.user/index.js
lively.user/user-flap.cp.js

The check we currently have for the availability of GitHub pages did not result in correct values for collaborators in a repository of a paying user, as well as for organizations. This PR:
1. Solves this issue, as we know that a user needs to create a repository/project themselves. We can therefore persist this information in the lively config and update it regularly (in case a users upgrades to paid after the fact). This way, we get correct results in all cases.
2. Fixes some problems with the code I introduces when I recently "resolved" some merge conflicts.
3. Fixes a problem where the loading indicator was not visible for long enough when creating a project, which could be quite confusing.

Enhance check of availability for GitHub Pages

---

lively.ide/studio/controls/shape.cp.js

There was a typo in the logic of the resize mode control of the side bar. It failed to set the `fixedWidth` of a text morph if instructed to do so.

🧰: fix typo in fixedWidth control

---

lively.ide/components/change-tracker.js
lively.serializer2/plugins/expression-serializer.js

We currently have several internal underscore style properties which have been introduced as part of #538. These incorrectly got reconciled upon component definition creation.

🧰🎨: ignore underscore style props in reconciler

---

lively.project/project.js

This fixes a bug that I recently introduced when I removed the regeneration without recognizing it.
Previously, we regenerated the CI files whenever we saved the `package.json` of a project. However, since they only become impactful once they hit GitHub, I think doing this when we actually save (and thus push) a project is a better idea.

[IMPORTANT] 📂: add missing regeneration of pipeline files saving project

---

lively.morphic/morph.js

Fixes the rendering of path/polygon morphs when positioned by css layouts.

🎨: fix order rendering of paths in css layouts

---

lively.morphic/layout.js

Previously, the effect of the resizePolicies came after the Text had already fit itself. Since the flag was not set, wrong extents manifested itself afterwards.

🎨: refit `Text` after resizePolicies` of `TilingLayout` kicked in

---

lively.project/templates/build.js

Since #1002, we need to change the configuration of the `jsonPlugin` in the bundler. This PR generates a working `build.mjs` for newly created projects.
See https://stackoverflow.com/a/10042082/4418325 for why we need so many backslashes.
---
This PR showcases a problem that occurs with generated but customizable files: We sometimes would need to regenerate a file in order to keep everything working. However, we cannot just nuke the `build.mjs` file of each project on save, as people might have made customizations to their build, e.g., by excluding additional modules. How do we want to handle this? Do we want to handle this? Would a visible hint inside of release notes eventually resolve this problem? Or a button that forces updates but that would one need to press explicitly? In the last …

📂: update generated build script for `lively.project`s

---

lively.morphic/rendering/renderer.js

For ominous reasons, the canvas inside the rendered canvas morph would not accept any pointer events. This made it impossible for some 3rd part libraries to work properly.
We hereby enable events on the canvas.

🚨allow pointer events on canvas

---

lively.ide/world-commands.js
lively.project/project.js
lively.project/prompts.cp.js
lively.shell/git-client-resource.js

Previously, it was possible to create effectively empty commits, since one could always press the save button, which in turn would lead to an increase of the patch number of the projects version, which then could be commited. We prevent this now, by just not opening the save dialogue when no files in the project have changed.

📂🧰🐚: do not create empty commits in projects

---

lively.ide/studio/font-manager.cp.js
lively.ide/studio/top-bar.cp.js
lively.ide/world.js
lively.project/project.js
lively.project/prompts.cp.js
lively.shell/git-client-resource.js
lively.user/index.js
lively.user/user-flap.cp.js

Previously, one could only create a remote repository for a project while creating the project. Afterwards, this option was not accessible for the average `lively.next` user, but only with some knowledge about how `lively.project`s work internally.
This PR changes that:
When one has a project that only exists locally, instead of the "Project Settings", which are only available with a remote, an option to add a remote appears in the save menu:
Clicking that will open the prompt that can be seen in the screenshot. There, one can choose if the repository should be private or not. Pressing OK will then create a repository, commit the changed config and pipeline files (and leave unsaved progress in the rest of the project alone) and push that to GitHub.
Afterwards, the "Project Settings" are …

Add remote after project creation

---

lively.freezer/src/loading-screen.cp.js

When opening the save menu of projects for the first time, the default emoji font of the system was used until "Noto Emoji" was loaded. As my default font is colored, and we use a bw emoji font, that was quite striking. Preloading the font in the loading screen already fixes this problem.

❄️: preload "Noto Emoji" font to prevent default emoji font showing

---

lively.freezer/package.json
lively.freezer/src/bundler.js
lively.freezer/src/resolvers/browser.js
lively.freezer/src/resolvers/node.cjs
lively.morphic/rendering/fonts.js

Fixes the issue that within bundles `availableFonts()` would not return the correct result, since there is not project loaded inside the bundle. The solution is to statically compile the available fonts into the bundle.

❄️🎨: compile available fonts statically into bundle

---

lively.ide/studio/top-bar.cp.js
lively.ide/world.js

When scrolling the world to the right via a touch input (trackpad on a laptop) this can trigger the back navigation gesture on some devices (at least mac OS). We not disable this feature by patching the document body inline style when the canvas mode is enabled on world load.

Disable navigate back gesture in browser on swipe input

---

lively.lang/string.js

Previously `string.isUUID(string.newUUID())` would return `false`.

📙: fix isUUID()

---

lively.ide/world.js

This add the option to not only register a fileResource with a callback to the `FileWatcher` but, also a regex. Each time a file is saved, all actions that are registered for regexes that match the whole url of the file to be saved get executed.

Add support for `RegExp` to `FileWatcher`

---

lively.ide/text/rich-text-commands.js
lively.morphic/text/morph.js

🧰🎨: enable `reactsToPointer` on `Text` when interactively editing

---

scripts/test.js

Previously, running tests.sh without specifying a package would create this file, which is only needed to create the formatted markdown summary on GitHub.

🛠️: prevent creation of `summary.txt` when running tests locally

---

lively.ide/world.js

We let obviously erroneous code slide through the PR in #1044.

🧰: fix invalid code in `FileWatcher`

---

lively.ide/js/eval-backend-ui.js

This resulted in an inform morph being generated each time one opened the browser or the workspace, containing a message about the currently selected eval backend.

🧰: fix incorrect signal input when setting `currentBackend`

---

lively.ide/world.js

Something that was super annoying up till now, is that world menus would appear not necessarily within the visible bounds of the world, having them cut off often when working on smaller screens. This fixes that, by moving the menu into the visible bounds to the extent its possible. It relies on `whenRendered()` since layouts are updating their bounds in an asynchronous fashion.

🧰: align world menus within visible bounds

---

lively.components/widgets/mode-selector.cp.js
lively.freezer/src/bundler.js
lively.ide/assets.js
lively.ide/components/helpers.js
lively.ide/studio/asset-browser.cp.js
lively.ide/studio/asset-manager.cp.js
lively.ide/studio/component-browser.cp.js
lively.ide/studio/controls/component.cp.js
lively.ide/studio/controls/fill.cp.js
lively.ide/studio/controls/text.cp.js
lively.ide/studio/properties-panel.cp.js
lively.ide/studio/top-bar.cp.js
lively.ide/text/rich-text-editor-plugin.js
lively.ide/world-commands.js
lively.ide/world.js
lively.morphic/components/policy.js
lively.morphic/morph.js
lively.project/project.js

Adds an "Asset Browser" which can be used to browse, instantiate and add assets inside of Projects or Playgrounds.
Currently, images are supported.
The browser can be opened via the top-bar or via the sidebar, when one has an image focused. Changing the imageUrl of an image via the sidebar does also reconcile into components, using `projectAsset` where applicable.
This closes #537.

Add "Asset Browser"

---

lively.ide/studio/properties-panel.cp.js

🧰: do not clear focus of `PropertiesPanel` when grabbing `targetMorph`

---

lively.ide/studio/controls/fill.cp.js
lively.ide/studio/top-bar.cp.js

This fixes a problem with the image controls from #1061, which are currently not correctly hidden when a non-image morph is selected.
Additionally, I fixed a problem in the top-bar, where usage of `get` instead of `getSubmorphNamed` led to incorrect results due to multiple morphs with the same name.

🚨: image control in properties panel is always visible

---

flatn/flatn-cjs.js
flatn/package-map.js
lively.freezer/src/loading-screen.cp.js
lively.freezer/src/util/bootstrap.js
lively.ide/studio/component-browser.cp.js
lively.ide/studio/world-browser.cp.js
lively.ide/world-commands.js
lively.ide/world.js
lively.modules/src/packages/package-registry.js
lively.modules/src/packages/package.js
lively.morphic/helpers.js
lively.project/project.js

This PR adds support for forked `lively.project`s. This way, it is possible to collaboratively work on a lively project without the need to set up a shared repository. This will be valuable for e.g., the partsbin, as it allows for a fork -> change -> PR -> merge workflow.
To achieve this, the following changes were made:
As we cannot change the contents of the `package.json` in the fork without creating a change that would propagate into the upstream repository, we create a `.livelyforkinformation` file which is hidden and on the `.gitignore` of projects by default. In this file we store information about the owner of the forked repository at the time at which the fork is cloned. As a fork needs to be created on GitHub, we are guaranteed to have this information (along with information …

Add support for forked `lively.project`s

---

lively.freezer/src/loading-screen.cp.js

#1038 Accidentally broke the missing world indicator. This is now fixed.

❄️: fix missing indicator in loading screen

---

lively.freezer/src/landing-page.cp.js
lively.ide/studio/world-browser.cp.js
lively.project/project.js
lively.shell/git-client-resource.js
lively.user/user-flap.cp.js

This adds the possibility to delete the remote of a lively project as well, once the project gets deleted.
As currently the only place to delete projects is on the landing page and one needs to authenticate with GitHub to delete a repository, this meant including the user flap on the landing page once more. In order to use `$world.inform` as part of the login process, we needed to adjust the `WORLD_CLASS` of the landing page.

Add option to delete remote when a local project is deleted on landing page

---

lively.project/project.js
lively.project/prompts.cp.js

Previously, the `ProjectCreationPrompt` was visible for a very long time when initializing a project from a remote, resulting in a confusing user experience. Now, the prompt disappears once the clone was successful and the loading indicator for the loading of the project takes over. This is more consistent with the way it happens when creating a local project as well.

📂: clear project creation prompt after clone has been successful

---

lively.ide/studio/world-browser.cp.js
lively.project/project.js

When I changed how the available projects are populated in #1072, this feature went under the rails: We will now sort the available projects alphabetically after their name again. I also included more keys than just the project name in the search: It is now possible to filter by projectname, projectauthor, projectowner, and description.

🧰📂: sort projects by name and allow filtering by all meta data

---

lively.ide/studio/component-browser.cp.js
lively.shell/git-client-resource.js

When one had a created a custom stash inside of a project (by using git via the command line as a programmer), that stash would be automatically popped once one pulled the latest version of the project. Now, the stash will be preserved and we only pop what we stashed ourselves.

🐚: do not accidentally pop custom stash when updating a project

---

lively.project/project.js
lively.shell/git-client-resource.js

GitHub does only grant 10 tokens per oAuth-App/User combination. One gets a new token every time one logs in. This means, that after 10 login-logouts in lively, projects that still have an old token baked into their URL wont work anymore, as the token is revoked.
To mitigate this problem, we just always bake the currently logged in token into all remote urls once a project gets loaded. **Note, that this effectively makes a local lively install/locally running lively server a single user application at the moment, and logging in with multiple accounts could have unexpected consequences.**

Update Tokens in remoteURLs upon loading of Project

---

lively.project/prompts.cp.js

Previously, there was a bug where one could login on the landing-page, press the new project button and the creation prompt would ask for a new login, due to a race condition. In all other instances, the login would be detected correctly. This removes the race condition.

📂: fix that `ProjectCreationPrompt` did not detect logged in user

---

lively.components/toggle.cp.js
lively.freezer/src/landing-page.cp.js
lively.freezer/src/util/bootstrap.js
lively.ide/offline-mode-toggle.cp.js
lively.ide/studio/top-bar-buttons.cp.js
lively.ide/studio/top-bar.cp.js
lively.project/project.js
lively.project/prompts.cp.js
lively.user/user-flap.cp.js

This PR makes it possible to work with projects without an active internet connection. Right now, this needs to be actively enabled by the use, by toggling the offline mode either on the landing-page or in the top-bar.
Doing so will give the user some information about the restrictions in offline mode.
In offline mode, the following happens:
- When creating a new project, no github repo can be created.
- No projects can be created from a remote URL.
- Loading a project will not pull the corresponding repository.
- It is not possible to add a remote to an existing project.
- Saving a project will not push the project.
- Updated user data will not be available, but a logged in user stays logged in when toggling offline mode.
- Logging out the user while being in offline mode requires an …

Add Offline Mode

---

update.sh

@merryman recently reported that the updating script did not work on his macOS system and there seemed to be a problem for some windows (WSL) users as well.
The problem was that the previous version of this script implicitly assumed a specific ordering of the output lines, which were not guaranteed. This was necessary in the first place, as at runtime of the command, the `grep` process itself as well as the shell process executing the whole command will show up in the output of the initial command.
By filtering those out, we guarantee the output at this point to only have two lines, which will make us resilient against any differences in ordering behavior between different platforms/implementations.

🛠️: fix inconsistencies in `update.sh` between different platforms

---

lively.user/user-flap.cp.js

This was an oversight in #1095, resulting in the user flap not showing the correct user data, even though that existed.

👤: display current user data when no updated user data is retrieved

---

lively.freezer/src/landing-page.cp.js

This is not yet a really solid relayout routine, but this at least fixes an error that appeared when the size of the window was changed on the landing-page, as it has `reactsToVisibleWindow` set to true which warrants a `relayout` function.

❄️: expose `relayout` on landing page

---

lively.morphic/rendering/renderer.js

Previously we would always consider a line to be wrapped by comparing the tallest char bounds of the line to itself which always returned true.
Fixes: #1021.

🎨: fix line wrapping detection

---

.github/workflows/check-deploy-docs.yml
.github/workflows/check-pr.yml
.github/workflows/daily-ci-checks.yml
.github/workflows/pr_labeler.yml
README.md
lively.ast/package.json
lively.modules/src/cache.js
lively.modules/systemjs-init.js
lively.project/templates/build-upload-action.js
lively.project/templates/deploy-pages-action.js
lively.project/templates/test-action.js

Fixes: #1116.
It appears the fact that we kept importing `jspm.dev` shipped version of `acorn-loose` and `acorn-walk` from the node.js context, finally took its toll and a recent change to the code that ships from `jspm.dev` wrecked havoc in the node.js runtime (namely: deleting the global Buffer object).
Whats interesting to note here, is that this error only occurs if the esm_cache does not carry a version of `acorn-loose` which makes me wonder why this error was not caught by the daily lively.next github action. I tried re-running it with a cleared cache and even that did not seem to raise the error reported in #1116. Any ideas @linusha ?

🚨 Fix crash at initial population of esm_cache

---

scripts/lively-next-flatn-env.sh

Not setting this could lead to build failures when running `make artifacts` and friends due to a heap overflow, especially on machines with little RAM.

🛠️: increase default memory of `v8` to ensure build process can run

---

lively.ide/studio/properties-panel.cp.js

📂: fix unsave access causing errors deleting sidebar target with halo

---

lively.freezer/src/util/bootstrap.js
lively.ide/components/editor.js
lively.morphic/components/core.js

Is a correction to #1105 where we apparently failed to properly revive component modules.

🎨🧰: properly handle component reviving and addition of unbundled changes

---

lively.ide/world.js

🧰: prevent numerical names from being used as playground names

---

lively.morphic/rendering/renderer.js

This reverts commit 5d1bcd7c5fce5e5122e6b6f30b879dcfec523c9e.
Somehow, the issue of left-to-right-wiggling text in wrapped lines could not be reproduced anymore. However, our change lead to the text not updating correctly the transform on the `scrollWrapper` when navigating a file via the muller columns of the system browser.

Revert "🎨: prevent cursor from moving text when moving over wrapped line edge"

---

lively.morphic/morph.js

Does the following things:
1.) Makes the computation of the owner chain less memory intensive.
2.) Caches the owner chain, so unnecessary recomputes are skipped.

🎨: cache ownerChain

---

lively.project/templates/build-upload-action.js

Just bumping this as there is a new version. More housekeeping than anything else.

📂: update to `v4` of `upload-artifact` action

---

lively.ide/studio/controls/border.cp.js
lively.ide/studio/controls/layout.cp.js
lively.ide/studio/controls/popups.cp.js

Fixes the broken guarding of values in a lot of the number controls in the side bar.
This was due to a botched migration of the number widgets to a view model implementation, where we forgot to adjust the parametrization like this: `..., viewModel: {...} `

🧰: properly parametrize number widgets

---

lively.freezer/src/util/bootstrap.js

Previously, `lively.collab` would not get properly *extracted* during the bootstrap process, leading to broken reviving issues.

❄️: extract lively.collab in bootstrap

---

lively.morphic/rendering/animations.js

Animations that would use a `customTween` (both internally and by explicit parametrization) would not cause their changes to be registered as overrides in the style policies. This lead to funky behavior such as buttons disappearing (as can be witnessed in the inspector right now).

🎨: ensure custom tween changes are recorded in animations

---

lively.bindings/index.js

Currently the right hand side bar can not be opened any more, since some code tries to signal `null`.
I thought that instead of adding defensive checks for any instances of `signal(obj, ...)` we just make `signal()` itself resilient towards falsy objects getting passed to it.

🎀: do not signal falsy objects

---

.github/workflows/daily-ci-checks.yml
scripts/test.js
scripts/test.sh

This fixes #1125.
This makes it so that we construct the summary manually in a separate step, which should always work. I still believe that the previous state did not work as intended is a bug, as multiple summaries per step and job are in theory possible and should be output in order, as per the GitHub documentation.
However, while at it I discovered some half-implemented features in the scripts and cleaned that up. When running the script locally, nothing should have changed. Running the script in CI it will now output the overall stats for all tests but also a list of all failing tests. The result can be seen here: https://github.com/LivelyKernel/lively.next/actions/runs/7424378787.
---
**This was estimated with 2 hours by both of us. This PR took 4.5 hours.**

🛠️: circumvent buggy github action summary by building it manually

---

lively.ide/js/inspector/index.js

This fixes a nasty bug which lead to widgets being positioned at the top left corner of the world. The reason for this was that the binding which closes open widgets on scroll kicked in too early, which messed up the correct fading into the world of the widget. Delaying the setting of the open widget resolves this, as then the binding cannot kick in prematurely.

🧰: stop open widget from being removed prematurely

---

lively.ide/components/editor.js

For components where `master: false` in order to invalidate inherited styles, the `InteractiveDescriptor.getDependents()` method would crash when component modules got saved.

🧰: fix crash for dependents with master: false

---

lively.ide/world.js

This was an oversight from #1185. The condition that checked if `label` was an object would also return `true` if the label was an array since an array is also an object!!! Bug from hell.

🚨🚨🚨 Fix for broken Github login flow

---

lively.components/prompts.cp.js

This is necessary for https://github.com/engageLively/galyleo-dashboard/pull/187. Also, it just makes sense to allow programmatic changes to these values and thus they need to be part of the official interface, which is given by `expose` via convention.

🎛️: expose `title` and `text` props of prompts

---

lively.components/prompts.cp.js
lively.ide/components/editor.js

@merryman as discussed, this basically reverts d2623f110d5ed5175d39165efe5b12fb6af20c95. The behavior of the safe-navigation operator (`?.`) does only cancel the access on `null` and `undefined` - this lead to an access on `false`. For cleaner semantics, we exchange this usage of `false` with `null` here.

🧰🎛️: use `null` instead of `false` when resetting master

---

lively.freezer/src/util/load-template.html
lively.morphic/text/morph.js

If I remember our conversation about this correctly, the problem here was that we sometimes retrieved a `true` from `documents.fonts.check()` even though the font was not actually loaded yet, as the fonts CSS was not even loaded so far that the checked font was part of the `documents.fonts`.
Despite the comment I removed saying otherwise, this behavior is [not actually a bug](https://developer.mozilla.org/en-US/docs/Web/API/FontFaceSet/check#nonexistent_fonts) but consistent and logical behavior.
We spoke about using `check` only for fonts that are guaranteed to be part of the `FontFaceSet`. `FontFaceSet` provides a `has` method which I tried to use, but the `value` this method expects needs to be a `FontFace` object which we cannot just create on the fly based on a font name.
As we have …

🎨❄️: improve `whenFontLoaded` performance

---

lively.ide/studio/version-checker.cp.js
lively.project/prompts.cp.js

The `VersionChecker` in the bottom left corner will now show a fitting message if lively is in offline mode and therefore possibly information regarding the status of lively will be retrieved.
Additionally, I removed the commit copy button when an error occurred.
Where possible we use the most recent local information when accessing the version information, e.g. when checking if the version of lively a project uses needs to be updated.

Add OFFLINE_MODE toggle for `VersionChecker`

---

.github/workflows/check-pr.yml
flatn/flatn-cjs.js
scripts/check-build-status.py

Instead of the highly involced logic used previously, we just try to rebuild the artifact (if that already fails - bad news) and compare the MD5 checksum of the committed and new bundle.
Closes #699.
See that this finds how the installer cannot be bundled anymore here: https://github.com/LivelyKernel/lively.next/actions/runs/7532330435/job/20502689702?pr=1197.

🛠️: rewrite artifact checker script to simply compare checksums

---

lively.morphic/morph.js

Fixes an issue where the transform of polygon morphs would not be rendered correctly.

🎨: fix polygon transform origin property notation

---

lively.components/tree.js

The boolean controls in the inspector do not update their font color anymore. This is because in the tree logic, we mess quite a bit with the renderer. This solves this problem, but is quite hacky - if it makes stuff worse, I do not know. @merryman what do you think?

🧰: forcefully update font color of `BooleanControl`

---

lively.ide/js/browser/index.js

Previously, it was possible to select the already browsed module via Alt+T, which would result in the muller columns blanking upon hitting enter. This makes it so that the entry can still be selected via Alt+T, but the `browse` method will notice that nothing is to be done and return early, rescuing the columns.

🧰: prevent browser from browsing already selected module

---

lively.ide/studio/dark-color-picker.cp.js
lively.ide/styling/color-picker.cp.js
lively.ide/styling/color-picker.js

Fixes the broken encoding selector in the `ColorPicker` and unifies the appearance of the encoders.
@merryman please take a look at especially two changes:
1. The `DarkColorPicker` was assigned as its own master. I believe this was totally bonkers - am I missing something here?
2. I believe the `DarkColorPicker` showcases a bug in the component system. As you can see, I had to make a lot of changes (e.g., regarding the `fontSize`) in the dark variant as well as in the light variant. As the dark variant inherits from the light one, I believe this to be bug.

Fix styling and encoding selector of `ColorPicker`

---

lively.ide/js/browser/ui.cp.js
lively.ide/world-commands.js
lively.morphic/CommandHandler.js

This PR started with me wanting to introduce a loading indicator while the browser is loading/setting itself up (remember, we talked about this, @merryman). While at it, I discovered that commands already allowed a `progressIndicator` to be specified and in theory automatically display this. However, for asynchronous functions, this did not work as expected, as they are removed too early. Making the whole command handling asynchronous would be an extremely intrusive change in the system, so that option was off the table.
Instead, we can access the loading indicator from within the command function and just take care of there. To do this, I introduced a new property that a command can have  `handleLoadingIndicator`.
While I was working on that part of the system anyway, I fixed some …

Fix interaction between loading indicators and commands

---

lively.components/list.js
lively.ide/studio/controls/text.cp.js

The bug could easily be observed when looking at the tooltips in the fontfamily selector after scrolling down a bit. The problem here is that at the place where we set the tooltip, we already know that we are displaying a **new** item. Reusing the tooltip from `this` is thus bound to lead to invalid values, as we need to use `item` since both are guaranteed to be different items.

Fix Dropdown Tooltips

---

flatn/module-resolver.js

Fixes a crash that would occur if entering commands in the shell terminal that would utilize the `send-to-lively.sh`.
`cd` was one of them.

🫓: fix exports resolution in package.json

---

lively.components/tree.js

Round two. This one should resolve #1229.
The basic idea here is to simply not cache colors that are equal to the selection color of the tree. The main issue here is though that there is no easy way to distinguish between attributes that were introduced by the selection mechanism and such that were manually set by the *user*. We solve this by placing a meta tag inside the attributes when setting the selection color inside the tree!

🎛️: prevent selection colors from entering color backup in tree

---

lively.ide/world.js

#1200 broke invocation of the halo when Ctrl+clicking on a morph which was not a direct descendant of $world, but was contained in another morph. This fixes it.

🚨: fix halo cycle

---

lively.morphic/events/EventDispatcher.js
lively.morphic/morph.js
lively.morphic/tests/input-event-test.js
lively.morphic/text/morph.js

There are three things, all require some thoughts and testing, @merryman:
1. I preemptively leave the `onMouseDown` handler if the clicked button is  the right one. Please test if this works on your machine as well. I remember that we had something similar in the past, but ran into problems with regards to platform compatibility!? Another thing is: In theory, executing `onMouseDown` upon a right click is not wrong. However, I'd argue that we basically always use `onMouseDown` as 'left mouse button down'. What do you think? I encountered this problem because a lot of behavior can be toggled with the right mouse button, for example the side-bar flaps, which is unexpected imo.
2. This should be the least controversial one - just a fix for previously broken behavior of text that we never …

Improve UX of right-clicks

---

lively.freezer/src/util/bootstrap.js

Fixes a visible failure in the `console`, introduced due to the `projectName` being set when a new project is created.

❄️: surpress `fetchInfoPreflight` when creating a new project

---

lively.ide/js/browser/ui.cp.js

I often had situations where I had halos open inside of a component to reconcile some changes and afterwards a "ghost halo" remained, as I closed the component when I was done. I believe this was not an issue before #1200, but now it was annoying.
The solution is to just close all halos related to the currently edited component once the editing session is to be terminated.

🧰: close all halos belonging to component when closing component

---

flatn/flatn-cjs.js
lively.resources/src/fs-resource.js
lively.resources/src/helpers.js
lively.resources/src/http-resource.js
lively.resources/src/local-resource.js

This should solve #174 once and for all. Mind, that this of course makes it so that the actual writable contents inside of lively are now reduced. We talked about this and decided that people that actually require a specific line ending to be used for stuff to work are on their own. :clown_face:

🪨: make sure to only write one type of line ending to disk

---

.githooks/commit-msg
scripts/commit-msg-length-emojis.js

As graphemes are not correctly counted in most programming languages without using a librabry and Git🐙 bundles its own `node` version that hijacks the hooks so that we cannot use the new `Intl.Segmenter` API, this is a functioning workaround. The previous behavior became really annoying.

🛠️: correctly measure the length of commit messages with emojis

---

lively.modules/src/module.js
lively.modules/src/system.js

Removes a cycle that would cause reviving of modules to crash and break classes in the system.

🧩: remove cyclical import that breaks reviving

---

flatn/flatn-cjs.js
lively.resources/src/helpers.js

Fixes a crash that would happen if attempting to upload files in lively. Oversight from #1239.

🪨: fix linebreak removal crash when encountering buffer objects

---

.gitignore
install.sh
lively.freezer/src/loading-screen.cp.js
lively.freezer/src/util/bootstrap.js
lively.ide/studio/component-browser.cp.js
lively.ide/studio/dialogs.cp.js
lively.ide/studio/world-browser.cp.js

Adds a button that allows to open snapshots directly from the landing page, without the need to know the magic URL options lively provides.
In the case the snapshot to be opened is not already inside of the `snapshot/` dir of the lively folder, we upload it there and open if afterwards.
Should also take care of the fact that fast load toggling with snapshots did not work previously.
@merryman please take a look, at the transition from the world browser to the loading screen when opening a snapshot - it look laggy to me, but I am not sure if that is just my machine or if I introduces a bad animation?
Closes #980. **This was estimated with 2d. Until opening the PR, less than 8h were spent.**

Loading Snapsopt via GUI

---

lively.components/list.js

Closes #1067.
The new options is enabled by default and forces the position of the menu to be inside of the visible bounds of the world.
https://github.com/LivelyKernel/lively.next/assets/14252419/98b74714-b184-4cd8-9176-70fe18226c67
**This was estimated to take 3 days and took less than two hours.**

Add `smartDropDown` to `DropDownListModel`

---

lively.project/prompts.cp.js
lively.project/templates/build.js

Fixes two problems with `lively.project`s:
1. Adapts the generated build scripts so that bundling is possible once more. @merryman uncovered a general problem: We currently generate this once (at creation time) and do not touch the script afterwards. This means that fixes like the one in this PR will not be automatically applied to already existing projects. We could now just force-create this with each save, thus guaranteeing that our fixes land in all projects. However, this will also override any customization one might have done to the bundling script. My proposed solution: We up the priority of #1223 and include therein thinking about a smart way of storing any customizations decoupled from the build script itself. Then, we can automatically generate an up to date and correct …

🚨: small project fixes

---

README.md
lively.server/plugins/dav.js
start-server.sh

Solves #1126.
Make sure to install `entr` according to our and their README when testing this. I have confirmed that this works on Windows machines with `WSL`. @merryman please confirm that everything works on mac.
There is one known problem that we need to fix before merging this: Sometimes, especially when many actions trigger `entr` often, there will be an error message like "Cannot write headers after sending response to the client" or something like that. Any ideas on how to solve this, @merryman?
Additionally, this solution triggers the hash creation probably too often. One could think about a more aggressive throttling for one. More importantly, changes from within lively should trigger this as well, as they need to write to disk. This is not nice, but I deemed it to be …

"Hot Reloading" 🥵

---

lively.git/index.js
lively.git/js-keygen/LICENSE.md
lively.git/js-keygen/base64url.js
lively.git/js-keygen/js-keygen.js
lively.git/js-keygen/pkcs1To8.js
lively.git/js-keygen/publicSshToPem.js
lively.git/js-keygen/ssh-util.js
lively.ide/studio/world-browser.cp.js
lively.ide/world-commands.js
lively.project/project.js
lively.project/prompts.cp.js
lively.project/templates/build-upload-action.js
lively.project/templates/deploy-pages-action.js
lively.project/templates/test-action.js
lively.shell/git-client-resource.js
lively.user/user-flap.cp.js

Closes #985.
This PR allows us to utilize the option of building/running tests in CI with projects that have dependencies.
The cases of public dependencies as well as private dependencies have been taken care of. In unusual circumstances (especially regarding multi-user usage of the same lively installation) it will be possible to break this. However, this scenario is rudimentary supported at best and really solving it would include a lot of security concerns which we decided not to tackle.
In general, the usage of private dependencies works by generating SSH keys in the browser and then using the private key as a secret inside of the project repository and uploading the public key to be used as a deploy key to GitHub. This way, the CI pipelines can authorize themselves to GitHub as being …

Dependencies in CI

---

lively.ide/text/search.js

Fixes an issue where the search highlights would remain in the text editor, when one changed the search string and directly afterwards closed the search widget. As the search operation is done with a slight delay, the highlights would then be kept around.

🧰: clean up search highlights if search widget is already closed

---

lively.user/user-flap.cp.js

This reverts commit e8b428b21c7c2619619780ce1412d4d1948b0cb4.
I just added "secrets" as a scope out of a gut feeling and never actually tested it, as I was always logged in. Turns out, that scope does not exist. What a :clown_face: fiesta.

🚨 Revert "👤: grant GitHub lively app permission to interact with secrets"

---

lively.freezer/src/bundler.js
lively.source-transform/index.js

This is a blunder as part of #1267 that broke the linter. We fix this by restricting the object preservation mechanism to the morphic config only.

❄️🔁: reserve top level object var preservation for morphic config

---

lively.project/project.js

📂: fix `saveConfigData` for offline mode

---

lively.ide/components/reconciliation.js

Fixes an issue where a fresh and empty component definition would not receive reconciliation changes.

🧰: prevent prop reconciliation crash on empty component

---

lively.ide/components/reconciliation.js
lively.ide/tests/components/reconciliation-test.js
lively.serializer2/plugins/expression-serializer.js

Fixes an issue where entering line breaks into a component text morph, it would mess up the source code during reconciliation.

🧰📇: properly escape characters when serialization txtAttrs to expr

---

lively.ide/components/helpers.js
lively.ide/components/reconciliation.js

Fixes an issue where erasing the entire contents of a text morph would not get reconciled.

🧰: fix text reconciliation when erasing entire text

---

lively.ide/text/map.js
lively.morphic/components/policy.js

Previously added morphs would just end up as an empty object in the spec.

🎨: fix ensure spec when adding plain morphs

---

lively.ide/world-commands.js

Previously, invoking the general command would just default to open a javascript workspace. However, we have a separate command for that so this behavior did not make much sense.

🧰: ask for language when opening unspecified workspace via command

---

lively.project/project.js
lively.project/prompts.cp.js
lively.project/templates/build-upload-action.js
lively.project/templates/deploy-pages-action.js
lively.project/templates/test-action.js

We recently discovered that enabling GitHub Actions follows a quite unintuitive logic where an action can only be triggered manually on a branch if its defining file also exists on the `main` branch. 
This was problematic as this meant that it is not possible to manually trigger a deploy from a branch inside of a project, without interfering with the main branch. However, deploying the branch is often useful for testing purposes.
Therefore, I have made the following changes:
1. We now create all workflow files all the time it makes sense to create workflow files.
2. By default, those need to be triggered manually. 
3. When triggering a workflow manually, the branch for which it is triggered is respected.
4. It is still possible to add a `push` trigger to the actions. This is only possible …

📂: enable actions by default and swap branch dynamically

---

lively.ide/studio/version-checker.cp.js
lively.project/project.js

We recently merged #1325 which was an absolute mess in hindsight.
We now utilize the already existing comparison mechanism, which I supplemented with a unique value for "empty" commit counts. Those will happen if we plugin a no longer existing commit hash in the comparison.

📂🧰: fix project version binding recovering from non-existing version

---

lively.ide/test-runner.js

Previously, opening the test runner before mocha-es6 was loaded (i.e., before opening a system browser) would crash and corrupt the global namespace in a way that would also wreck browsers opened later.

Fix mocha-es6 loading in Test Runner

---

lively.ide/studio/properties-panel.cp.js

Fixes an oversight from #1343.

🧰: prevent layout control from nuking layouts on unfocus

---

lively.ide/components/reconciliation.js

🧰: fix missing spec updating during text reconciliation

---

lively.ide/js/browser/index.js
lively.ide/js/browser/ui.cp.js

🧰: fix alignment of component edit buttons on line wrap

---

lively.ide/text/map.js

Fixes an error that occurred super often when using the search inside of the system browser and then cancelling the search via clicking outside of the browser.
It was not particularly harmful, but annoyingly spammed the console.

🧰: fix destructuring error

---

lively.ide/world.js

🧰: wait for layout to compute before opening morph in window

---

lively.morphic/rendering/renderer.js

This resolves an bug that only became apparent once one begins to ensure, that the `textLayer` is always the same node. Due to the `extent` getter measuring the text and us accessing width/height we triggered a measurement in the measurement, which fucked up the state of the node that is moved around inside of the placeholder for the measurement.
Preventing this behavior here has no downside to the measuring process, as we only access the width/height when the dimension is marked as fixed in the properties, i.e. we can retrieve a value guaranteed to be correct without measuring.

Fix Recursion when measuring static `Text`

---

lively.morphic/assets/morphic.css

Previously, the behavior of `break-words-only` was wrong, as it behaved like `by-chars`. 
For more information on the used CSS property see here: https://developer.mozilla.org/en-US/docs/Web/CSS/word-break

🎨: fix incorrenct behavior of different `line-wrapping` values

---

lively.installer/assets/localconfig.js

Small ease-of-life enhancement that allows for easier writing of localconfigs, as one does not need to remember `config` anymore.

📦: add config for improved ease of use

---

lively.ide/studio/controls/shape.cp.js

This makes it so that toggling the hug behavior via the sidebar immediately fits the text morph to its hugging dimension.

🧰: fit selected text morph if height/width set to hug

---

lively.ide/studio/controls/popups.cp.js

🧰: fix font size and padding issues in text control

---

lively.components/list.js

Fixes an annoying issue where resizing a scrolled list would lock in the scroll when the list was resized such that the scrollable area is exceeded by the new extent.

🎛️: update item scroll if list extent change

---

lively.morphic/rendering/renderer.js

Fixes #1362. To me this looks like a simple oversight?

🎨: fix path clipping svg in renderer

---

lively.morphic/rendering/renderer.js
lively.morphic/text/morph.js

When you are done reviewing this, I will rewrite the commit messages cleanly. Before that, we need to decide whether or not we want to squash all of these into one commit or not.

Use references instead of `querySelector` in most cases in renderer

---

lively.halos/markers.js
lively.ide/world-commands.js
lively.morphic/morph.js

Adds a helpful new feature, that I enjoy. We can now pass a color to `Morph.show()` that will allow us to highlight morphs in different colors giving for instance a visual cue to where `show()` was called from.

🧰🎨👼: add support for differently colored markers

---

lively.freezer/src/bundler.js
lively.modules/src/module.js
lively.source-transform/index.js

Resolves #1346.
Turns out this was nothing specific to commands but to modules with `default` exports in general.

❄️🧩🔁: fix reviving of modules with default exports

---

lively.halos/morph.js

A further refinement of  #1353. I also noticed that we lost the default behavior of the halo to keep that target selected once it has been dropped onto a new location.

👼: ensure halos stick around after drop via grab

---

lively.morphic/components/policy.js
lively.morphic/tests/components-test.cp.js

The `__wasAddedToDerived__` is a internal flag of a style policy to denote specs that are due to newly introduced morphs to a derived style policy. Erroneously it was carried over the entire derivation chain, even for style policies that had not altered anything about the structure of the defined component.

🎨: clear addedToDerived flag when morph inherited

---

lively.halos/components/messages.js

Fixes the following that happens for error messages with small text:

👼: prevent message title from being squashed for short expanded content

---

lively.freezer/package.json

The freezer threw a warning when one bundled without a populated server-side `.module-cache`

❄️: add `systemJS` mapping for `bowser`

---

lively.morphic/rendering/animations.js
lively.morphic/rendering/morphic-default.js

Cleans up some code that introduced complexity that is entirely unused after we do not use the `vdom` anymore.

🎨: remove `maskedProps` remnants after `vdom` removal

---

Makefile

For some changes (as of this PR we only now about the ones in #1416) it is important to clear the server side module cache, as otherwise the changes do not reflect in the bundles. We do not know for sure why that is.

🛠️: clear server side module cache when rebuilding artifacts

---

lively.ide/js/browser/ui.cp.js

Previously we would run into similar issues we already observed with the prompts, where large components whose ultimate extent is dictated by the layouts would get positioned completely incorrectly.

🧰: force layout in openend component morphs to ensure proper positioning

---

lively.ide/studio/top-bar.cp.js

A correction to #1422 which failed to fix the crashes in custom sub-classes of the top bar.

🧰: remove this binding from bindings in top bar

---

lively.project/prompts.cp.js

Fixes a funny issue where canceling the save project prompt would make it be gone **forever**.

Fix offended project save prompt

---

lively.ide/studio/scene-graph.cp.js

🧰: stop scene-graph from toggling halo that breaks text edit on creation

---

lively.project/prompts.cp.js

📂: fix advanced options flap in project save prompt

---

lively.morphic/text/morph.js

Fixes an issue where pasting text in a morph would not get reconciled.

🎨: reconcile paste changes in text

---

lively.morphic/text/icons.js

Adds a helpful helper function to the `Icon` class, that returns us the name of a given icon code.

🎨: add lookup function to Icon

---

lively.morphic/layout.js

🎨: exclude invisible morphs from margin computation in tiling layout

---

lively.ide/js/browser/commands.js
lively.ide/js/browser/index.js

Fixes a bug where the browser was closed regardless of whether one goes through with the module deletion or not. While that makes sense for when the currently opened module gets deleted, closing the browser when one wanted to keep the module is confusing and not helpful.

🧰: do not close browser when module deletion is cancelled

---

lively.ide/studio/controls/component.cp.js

Fixes an issue where in the presence of breakpoints inside a component, the comonent of a morph would sometimes be displayed as empty, although it wasnt:

🧰: do not display empty component control in presence of breakpoints

---

lively.morphic/morph.js

Makes it so that by default, images will try to fill the extent of their morph extent, but only in so far as their aspect ratio is respected. By setting `sizeToAspectRatio` to `false` the old default behavior can be achieved, which leads to the image filling its morph extent no matter what.

🎨: add `sizeToAspectRatio` to `Image`

---

lively.morphic/text/morph.js

🎨: add font name and morph name to error message for invalid font name

---

lively.morphic/text/morph.js

Fixes a problem that was visible when just putting `''` inside of a workspace and executing that code. The result was that the result of the expression was not correctly applied due to the empty string being falsy, displaying the placeholder text in the component message.

🎨: fix empty string not showing in status message when evaluating code

---

lively.morphic/text/morph.js

Text morphs that were controlled by policies would not properly hug their text content if configured to do so:
Before (wrong):
After (correct):

🎨: fix bogus fitting cancelation in response to policies

---

lively.ide/studio/asset-browser.cp.js

Fixes a problem where, when the windowed asset browser was open and the sidebar was used to change the asset inside of an image with the popup version of the asset browser, the windowed asset browser was getting blocked as expected, but merely confirming a new asset inside of the popup, did not clear the windowed version again.

🧰: fix asset browser blockage not being cleared

---

lively.components/window.cp.js
lively.morphic/layout.js

This fixes a crash that happened for instance when you tried to save `window.cp.js`.

🎨: crash when comparing layouts to non layouts

---

lively.ide/js/inspector/index.js
lively.ide/world-commands.js

When changing the inspectors target via Shift+Click, thus resulting in a list of all possible morphs showing, an error was triggered upon each selection. This PR fixes the problems.
This also makes it so that we filter the prompts included in the list so that only "custom"morphs are included and not tooling etc.

Fix changing the inspector target via `FilterableList`

---

lively.modules/src/system.js

Fixes a weird issue, where `lively.modules` tests would fail in slow load.

🧩: ensure trace flag in makeSystem() at all times

---

lively.serializer2/plugins/expression-serializer.js

Fixes the issue reported in #1498.

📇: do not consider parent master if no meta present during expr gen

---

lively.ide/js/browser/index.js

Fixes a bug that got introduced in #1496.

🧰: fix a bug where modules that needed to load first would not open

---

lively.modules/src/system.js

🧩: only trace system loads in resurrection builds

---

lively.ide/components/editor.js

Fixes an issue where the previous presence of an object like variable with the same name as a component definition would cause a crash when saving the module.

🧰: ensure previoust component desc is REALLY component descr

---

lively.ide/js/browser/ui.cp.js

Fixes an error that would sometimes appear in the log when navigating in the system browser.

🧰: fix crash on concurrent transitioning in browser meta info

---

lively.morphic/morph.js
lively.morphic/tests/components-test.cp.js
lively.serializer2/plugins/expression-serializer.js

Fixes a crash that would happen when creating a component definition from a morph structure.

🎨: declare master default value to be null

---

lively.ide/md/mode.js

This fixes a bug that existed in the old markdown mode where a blockquote was not correctly ended but instead went on until it found a leading space, which was incorrect behavior.

🧰: update md parsing code from codemirror to fix blockquotes not ending

---

lively.morphic/text/layout.js

Fixes the numerous warnings in the console that would happen when using text morphs with a document.

🎨: ensure line is measured via canvas when charBoundsOfRow() called

---

lively.morphic/config.js
lively.morphic/world.js

Made the color scheme configurable via `localconfig.js` while defaulting to the systems default value.

🎨: allow configuring color scheme via config

---

scripts/test.sh

See #1524 for more information.
:pray: :pray: :pray: :pray: :pray: :pray: :pray: :pray: :pray: :pray: :pray:

🛠️: move `lively.morphic` back into the middle of tested packages

---

lively.project/templates/build-shell.js

Small QOL improvement that puts a timestamp inside of the output of the build script of projects, so that it is easier to tell when one ran it the last time.

📂: add timestamp to output of projects build script

---

lively.freezer/src/util/main-module.js
lively.morphic/layout.js

Fixes a problem that manifested on my machine in Firefox where `Yoga` was not loaded fast enough, resulting in an unrecoverable crash when loading a bundled page.

🎨❄️: ensure adequate load time for `Yoga`

---

lively.ide/studio/world-browser.cp.js
lively.project/project.js

Fixes two problems with the `livelyIncludePartsbinInList` hidden option:
First, the check whether this was active or not was not working as expected, as the values retrieved from the local storage are strings.
Second, the option was also used when `listAvailableProjects` was used for reasons other than filling the project browser.
Both of these should now be resolved.

📂🧰: correctly use `livelyIncludePartsbinInList` in `localStorage`

---

lively.ide/world-commands.js

We recently changed `Text` to fit its content by default, which caused this command to produce funny-looking windows.

🧰: fix `open text window` command to fix text extent

---

lively.morphic/tests/text/layout-test.js

For some reason this leads to the CI pipeline running through. This is not a valid fix, thus #1524 remains open.

🎨: retry `layout` tests up to three times

---

lively.morphic/rendering/font-metric.js

Fixes a horrible oversight from #1510.

🎨: fix accidental textAndAttrs mutation during font measuring

---

lively.morphic/html-morph.js

Solves a problem where the extent of hugging `HTMLMorph`s got huge, due to a feedback loop.

🎨: fix computation of bounds for hugging `HTMLMorph`s

---

lively.project/project.js

📂: update bound lively version in pipelines on open

---

lively.project/index.js

Importing via the `index.js` file lead to bundled project not loading anymore.

📂: let `projectAsset` be imported from `helpers` file

---

lively.ide/components/reconciliation.js

Solved a problem for me where I just renamed a morph inside of a layout which crashed the reconciliation.

🧰: fix reconciliation when renaming morph inside layout

---

lively.morphic/components/core.js

**This is not yet fully fleshed out, and there might be cases where this messes up the reconciliation.** However, this feature is extremely handy as it allows us to build responsive components extremely fast, for example by swapping out layouts inside of complex morph structures without the need to extract partial hierarchies into separate components.

🎨: allow inline components for breakpoints

---

lively.morphic/rendering/font-metric.js

Fixes an issue, where the line wrapping would be computed incorrectly if the border style was set to `none`.

🎨: correctly compute wrapping space in presence of none borders

---

lively.ide/studio/controls/text.cp.js

Fixes a crash that happened when toggling a quote style in a selected piece of text.

🧰: fix quote toggling in richt text popup

---

lively.ide/js/browser/ui.cp.js
lively.ide/studio/tabs.cp.js

Removes a bunch of messy code that could be removed by introducing state masters.

🧰: handle selection styling in tabs via component states

---

lively.morphic/config.js

@merryman please check if this now also works on mac devices. I checked on my machine and the depicted keybinding now works as expected.
The reason for this keybinding not working on Linux/Windows machines before was that there was a duplicate keybinding between "Ctrl-Shit-E" and "Shift-Ctrl-E". I am not sure what the problem on mac might have been.

🎨: fix `editit` keybinding that was double-bound previously

---

lively.ide/studio/controls/border.cp.js

It does not make sense to control top,left,right,bottom border for shapes that just have a one dimensional border. So this will hide the "more" option from the border control in the sidebar.

🧰: do not show “more” border control for paths

---

lively.ide/styling/color-picker.js

Fixes an insane bug in the color picker, where using the eye dropper when selecting the color of a color stop in gradient mode would switch the entire color back to a uniform color.

🧰: do not switch back to uniform color if using eye dropper for gradient

---

lively.ide/studio/controls/constraints.cp.js

🧰: fix alignments in constraints simulator in side bar

---

lively.components/window.js

Fixes just plain wrong alignment code in the window resizer. Is no big deal, but made the resizers overlap at times, which is not ideal.

🎛️: fix computation of resizer alignment

---

lively.project/prompts.cp.js

Just a tiny QOL change that makes it easier to follow the creation of projects.

📂: indicate invalid input when leaving text field in project creation

---

lively.project/prompts.cp.js
lively.user/user-flap.cp.js

The initial problem I observed was that the login button was displayed when creating a new project but the rest of the prompt was not disabled. Investigating showed that we in fact had a valid access token stored, but no user data in the local storage. Since we only checked for a token in the prompt but for the user data in the user flap (which is responsible for the login button), the prompt thought that everything was fine and disabled nothing. So the first change here is just making this check consistent.
Additionally, I made it so that in cases where we find a token but no user info, we try to retrieve the user info from github and thus "recover" the login. In cases where the token is not valid, we abort this and properly clean up all remaining user data, thus leading to a new, clean …

Harden check for currently logged in user when creating a project

---

lively.morphic/rendering/fonts.js

Oversight from #1549. :clown_face:

🎨: add 'Noto Emoji Color' to list of supported fonts

---

lively.freezer/src/bundler.js

Something I introduced a while back that was too eager and that browsers do not like. We never caught it before, as we did not bundle video assets...

❄️: remove invalid `link` tags with `preload` attribute for `mp3` &`mp4`

---

lively.ide/studio/scene-graph.cp.js

previously the scene graph would no longer scroll if the number of items exceeded the visible space

🧰: fix scoll of scene graph

---

lively.components/list.js

This allows layouts to ignore the changes a list performs internally, which never affects other enclosing layouts anyways. This saves compute.

🎛️: classify list update as layout action

---

lively.ide/js/browser/ui.cp.js

This prevents erratic jumps of components that can happen due to delayed layout applications.

🧰: ensure component layouts applied before opening in world

---

lively.morphic/rendering/font-metric.js

Previously this would cause invalid values to be introduced into the canvas compatibility cache.

🎨: do not perform canvas check if font still loading

---

install.sh

When installing lively with `--freezer-only` flag, the classes runtime was previously not build. This leads to problems with more complicated builds like the website.

🛠️: compile classes runtime when installing only to freeze

---

lively.ide/md/editor-plugin.js

For whatever reason the default editor commands (including the super useful toggle comment command) where never included in the markdown editor plugin. This fixes that.

🧰: integrate general editor commands in markdown editor plugin

---

lively.ide/md/compiler.js

Allows to use `HTML` code inside of `md` documents.

🧰: add option to embed `HTML` in markdown

---

lively.morphic/rendering/property-dom-mapping.js

This reduces dom operations on world resizing events.

🎨: render width and height via 100% if world resizing is elastic

---

lively.morphic/world.js

Avoids crashes when opening ide specific tools are used in vanilla worlds (i.e. frozen apps).

🎨: add top bar callback stub to vanilla world

---

lively.freezer/src/bundler.js
lively.freezer/src/landing-page.cp.js
lively.freezer/src/util/helpers.js
lively.modules/src/module.js
lively.morphic/world-loading.js

Fixes the server bug in #1643.
After we merged 9741894, there was a serious bug uncovered that happened to never surface before.
Concretely it was a bug with reviving of modules where we re-execute the split bundle parts in order to inject updated entities of changed modules into the frozen bundle.
This was buggy, since during re-execution of the bundle parts, the `System` variable would no longer be the one that was used during initial load. This is because the System we use gets swapped out after bootstrapping is done.
We now had a situation where reviving would ping pong between two different instances of System causing crashes.
I really do no entirely understand why this ping pong situation was avoided until this commit.
What appears to have caused it was the removal of a remaining …

🚨🚨🚨 Fix/frozen module reviving issue

---

lively.ide/md/morphs.js

Enabling this flag allows us to force correct behavior on the documentation pages for the new website while minimizing the risk to interfere with anything else using the markdown preview morph.

🧰: add flag to disable scrolling inside of `MarkdownPreviewMorph`

---

lively.freezer/src/bundler.js

Previously the exclusion mechanism would mostly just declare excluded modules as externs, which would not really shim the missing exports. This new mechanism just returns empty source strings for excluded modules, which leverages the module shimming in rollup.js

❄️: properly exclude modules in freezer

---

lively.ide/md/morphs.js

Otherwise, some of our documentation pages would error once we exclude the linked css, which alters the node structure of the result.

🧰: decouple markdown compilation from concrete node structure

---

lively.ide/md/morphs.js

Fixes an issue where code highlighting was broken for markdown files that did not contain interactive elements.

🧰: run highlighting code after html export of markdown

---

lively.ide/md/editor-plugin.js

Previously, just saving a `md` file lead to an error, as the loading indicator could not find the world of the (non-mounted) preview window.

🧰: only show loading indicator for markdown render when window present

---

lively.ide/md/morphs.js

Fixes an oversight from #1557.

🧰: also apply syntax highlighting after render of simple markdown

---

lively.ide/shell/terminal.js

For the longest time It was quite inconvenient to have to scroll sideways to see long lines in the terminal fully. This enables wrapping by default for the terminal in lively.

🧰: wrap lines by chars in terminal view for convenience

---

lively.morphic/rendering/font-metric.js

Previously especially in text morphs with a large document such as the editors inside the system browser, overly eager checks for certain text style classes would cause the performance to tank. This can be avoided by first checking wether or not the text morph is hugging its text contents or not. In case of hugging, the measurment via canvas has to be dispatched to each line, since textwrapping is not supported on canvas.

🎨: avoid check for text style classes if not nessecary

---

lively.freezer/src/util/bootstrap.js
lively.ide/components/editor.js
lively.ide/components/helpers.js
lively.ide/components/reconciliation.js
lively.ide/js/browser/index.js
lively.ide/js/linter.js
lively.ide/world.js

I noticed that loading the eslint package either consumes a lot of time in the loading screen or when delayed, as soon as one opens the system browser, which is annoying. When loading from the bundle its super fast.
I suggest accessing the linter via a static function installed on the System object, which initially references the bundled eslint, which loads fast.
That way we can also benefit from fast eslint loading even in slow load.

❄️🧰: delay linter module loading to improve loading time

---

lively.freezer/src/landing-page.cp.js

❄️: wrap fast load toggle in separate container to fix alignment

---

lively.morphic/components/policy.js

Fixes the currently failing reconciliation tests.

🎨: properly carry over wasAdded flag in fully synthesized specs

---

lively.ide/code-search.cp.js

Fixes an annoying error when opening a code search and selecting the search input.

🧰: fix halo color in code search

---

lively.modules/src/export-lookup.js

In fast load, when browsing for modules exporting certain entities, it would display all kinds of matches that would not make any sense. This fixes that.

🧩: fix export lookup from frozen modules

---

lively.morphic/rendering/font-metric.js

Fixes an issue with #1717. Among other things, it cause the buttons in the properties side panel to look squashed:

🎨: fix attr based sizeFor() measurement in font metric

---

lively.resources/index.js

Fixes #1727, just to get rid of it.

🪨: remove unused param from `loadViaScript`

---

lively.ide/studio/top-bar.cp.js

🧰: enforce dragged polygon to have width and height of at least 2

---

lively.ide/studio/interactive-tree.js
lively.morphic/morph.js

This is mainly intended for @rickmcgeer's ease-of-life: It adds a property called `forceSceneGraphInclusion` which allows overriding the in-built criteria of the scene-graph. See #1452.

🎨🧰: add `forceSceneGraphInclusion` property for `Morph`s

---

lively.ide/studio/zoom-indicator.cp.js

Fixes this, with the same trick applied in #1689.

🧰: fix initial layout of zoom indicator

---

lively.ide/world.js

Fixes #1767.
Fixes #1763.
For cases where one decides to freeze an ide world, but wont utilize it alongside a bootstrapped module system.

🧰: ensure ide world becomes visible if never animated

---

lively.ide/studio/component-browser.cp.js

🧰: fix search icon in component browser

---

.gitignore

Just a tiny QOL thing. The offending file remained around after executing all tests once locally.

🛠️: put test artifact on `.gitignore`
