lively.ide/world-commands.js
lively.ide/world.js
lively.morphic/config.js

This closes #25, at least the concrete behavior that we talked about in the issue regarding the workspaces.

more descriptive workspace keybindings

---

lively.ide/world-commands.js
lively.ide/world.js

I am working on implementing #35.
The functionality should be given with the code that already exists (at least works on my maschine^^).
I will add:

add command to clear cache and indexdb

---

lively.ide/world-commands.js
lively.morphic/config.js

We could not verify that this works as expected on mac, since we do not have access to one. 
This closes #101

allow deletion of selected morphs with del-key

---

lively.halos/morph.js
lively.morphic/morph.js

When right clicking on a halo-selected morph, an error appeared. This PR fixes this.
The auto linter added a lot of additional changes.

Remove error on right click on morph with halo open

---

lively.morphic/text/label.js

Labels do not accept drops as default anymore

---

lively.morphic/events/Event.js

Co-authored-by: T4rikA <talnawa@outlook.de>

event: fix mousebutton detection

---

lively.morphic/events/Event.js

The fix suggested by @merryman in #200

Fix text selection

---

lively.morphic/world.js

world: set document title to world name

---

lively.morphic/config.js

Closes #26 
While this does not address the core of the problem, it does resolve that issue.

Fix backspace shift printing input

---

lively.ide/world-commands.js

world commands: correctly resize windows after reset

---

lively.lang/array.js

Introduces binary search for arrays. No performance tests carried out.

Add binary search to lively.lang/array.js

---

lively.components/list.js

Fixes not being able to paste into the global code searcher

list: do not bind Ctrl-V

---

lively.morphic/text/search.js

Change keybinding for windows of the command to find occurencies, so it is usable there

Fix keybinding for windows

---

lively.morphic/undo.js

undo manager: add better warning

---

lively.morphic/morph.js

Adds a tiny little signal to hook into the removal of Morphs.

morphic: add signal to hook into remove

---

lively.morphic/morph.js

morph: add evt to image menu items

---

lively.morphic/morph.js

I am not sure anymore what this actually fixes, but I know that @merryman and I wrote this to fix some weird behaviour, so I figured it would be good to place this PR

Fix master styling

---

lively.ide/value-widgets.js

Trigger relayout of NumberWidget

---

lively.collab/comments/commentBrowser.js
lively.collab/comments/commentMorph.js
lively.collab/tests/browser-test.js
lively.morphic/morph.js

Fix some of the tests of lively collab

Fix comment tests

---

lively.components/prompts.js
lively.ide/world.js
lively.morphic/morph.js
lively.morphic/text/label.js

@merryman I was a bit trigger happy with the last one.
@frcroth made a good point about this option being better suited to the opts of the input line as opposed to being their own argument.
I'd agree with this assessment. 
If you want, we could probably get rid of the previous merge commit to keep the history cleaner...

promtp: use inputline prompt for preselection

---

lively.halos/morph.js

halos: check if comment browser is open before updating name

---

lively.ide/js/browser/ui.cp.js
lively.ide/studio/controls/shape.cp.js
lively.ide/studio/sidebar-flap.cp.js
lively.morphic/morph.js
lively.morphic/object-migration.js
lively.morphic/rendering/property-dom-mapping.js
lively.morphic/rendering/renderer.js
lively.morphic/style-sheets.js
lively.user/morphic/user-ui.js

E.g. the top-corner can have a different radius than the bottom-right one.

Allow setting different borderRadius per corner

---

lively.lang/graph.js

The fully documented `lively.lang/graph.js`.

lang: add graph docs

---

lively.lang/graph.js
lively.lang/properties.js

The complete set of docs for `lively.lang/properties.js`

Property docs

---

lively.classes/object-classes.js
lively.classes/runtime.js
lively.freezer/src/util/bootstrap.js
lively.ide/studio/world-browser.cp.js
lively.ide/world-commands.js
lively.lang/object.js
lively.morphic/components/core.js
lively.morphic/serialization.js

This removes the top level dependency onto `lively.modules` within 'lively.morphic/serializer.js' and replaces it with a dependency injection mechanism.

Serializer modules decoupling

---

lively.halos/morph.js
lively.morphic/morph.js

Event that gets fired if mouse click on morph with halo activated

morphic: add onHaloMouseDown event

---

.github/workflows/check_builds.yml
README.md
flatn/build.js
flatn/build.sh
flatn/dependencies.js
flatn/download.js
flatn/flatn-cjs.js
flatn/index.js
flatn/module-resolver.js
flatn/package-map.js
flatn/package.json
flatn/resolver.mjs
flatn/tools/build-cjs.mjs
flatn/util.js
install.sh
lively.ide/studio/version-checker.cp.js
lively.installer/assets/update.sh
lively.installer/build.sh
lively.installer/package.json
scripts/check-build-status.py
scripts/ci-tests.sh
scripts/lively-next-flatn-env.sh
scripts/test.js

@merryman the script can already be reviewed :)
I am not sure if there is a better way, but currently we pull the whole repo and its complete history when this runs. This means we are burning quite a bit of bandwidth. Not sure if this is something where we can run into quotas, but it is bad for the :polar_bear:. :(
**Open Steps:**
@merryman did I miss something?

Build artifacts action

---

lively.vm/lib/eval-support.js
lively.vm/tests/eval-test.js
lively.vm/tests/lively-compat-test.js

Fixes all of the previously failing tests in `lively.vm`.

🎮: fix vm tests

---

lively.ide/js/browser/commands.js
lively.ide/js/browser/index.js
lively.ide/world.js

In the best case we merge this after merging #366.
Only the two commits that change files in `lively.ide` are important for this.

Improve behavior upon creation/deletion of packages in browser

---

lively.ide/code-search.cp.js
lively.ide/code-search.js
lively.modules/src/module.js

https://user-images.githubusercontent.com/14252419/177202355-394c8424-cf6e-4883-baa1-1e8a2adf26ea.mp4

🧰: Add buttons for case-sensitive and regex based search to code search

---

scripts/check-build-status.py

@merryman this fixes the blocker in #410

🛠️: Artifact checker succeeds when rebuilding would not change artifact

---

lively.user/tests/client-test.js

Makes the tests properly wait until server is closed before running next.

👤: fix user tests

---

lively.halos/morph.js

This fixes a leftover issue from #453 where the halo would still try to access side bars via the top bar.

👼: adjust to new sidebar access via world

---

lively.ide/world.js
lively.morphic/world.js

Fixes an issue where the world would not resize exactly to the browser window bounds when the browser window is resized.

🧰🎨: fix resizing to fit window in world

---

lively.ide/studio/sidebar-flap.cp.js
lively.morphic/world.js

Co-authored-by: Robin Schreiber <robin.schreiber@me.com>

🧰🎨: fix scrollbar appearing when leaving world bounds with hand/on flaps

---

lively.morphic/components/policy.js
lively.morphic/morph.js

🎨: fix reset of style when click + hover

---

lively.halos/morph.js
lively.ide/studio/properties-panel.cp.js

Closes the remainder of #518, most of it has already been solved.

👼🧰: unify signals upon halo removal

---

lively.ide/code-search.cp.js
lively.ide/code-search.js

Gets rid of the proportional layout from the code search. 
Also does some minor padding adjustments to the UI elements.

🧰: fix code search layout

---

lively.ide/studio/controls/border.cp.js
lively.ide/studio/controls/popups.cp.js
lively.ide/styling/shared.cp.js
lively.morphic/components/core.js
lively.morphic/rendering/morphic-default.js

Closes #347.
This is more of a proposal than something that I have a hard opinion on. The problem that the issues describes is obvious and I would think this is the canonical fix for it, however, I am not sure if this could have side-effect that I have not thought of that would cause problems.
In case you are not sure if this is problematic, I would probably vote for not merging this and closing the ticket as "won't do". I'd also assume, that the underlying reason for this occurring, opening popups in a rather crowded world, becomes less of a problem once we have the "endless scrolling canvas style world".

🧰🎨: move popups in front of halo

---

lively.ide/studio/top-bar.cp.js
lively.ide/styling/color-picker.js
lively.ide/world.js
lively.morphic/world.js

Small adjustment to the #519. I dont think we want a halo on the world. It almost always obstructs/confuses the user.

🧰: do not show halo for world

---

lively.ide/debug/console.cp.js
lively.ide/js/snippets.js
lively.ide/world-commands.js
lively.morphic/components/core.js

Carries over the previous parts based implementation of Console into a component based definition.

🧰: add debug console

---

lively.morphic/morph.js

As part of #538 this removes the `installedFonts` property from the morphs. Eventually we will migrate towards defining font dependencies inside modules and not attached to objects.

🎨: remove installedFonts property

---

lively.ide/text/map.js
lively.ide/text/search.js

A tiny quality of life improvement.

🧰: do not cancel search when code map is used while searching

---

.github/workflows/build_docs.yml
.github/workflows/check_builds.yml
.github/workflows/check_docs.yml
.github/workflows/check_world_loading.yml
.github/workflows/ci-tests.yml
.github/workflows/pr_labeler.yml
README.md
install.sh
lively.installer/assets/start.sh
lively.installer/install-with-node.js

Should capture the issue that was *again* encountered in #561.
@linusha We may need to update the GitHub Actions stuff as well inside this PR.

📦: bump required nodejs version in install.sh + start.sh

---

lively.components/window.js

🎛️: fix wrong window state when opening sub-windows

---

lively.morphic/rendering/morphic-default.js

**Before:**
https://user-images.githubusercontent.com/14252419/211808246-06d87546-598b-48a6-9a76-dc2dac2f0c16.mp4
**After:**
https://user-images.githubusercontent.com/14252419/211808242-f183b2ec-2631-4b07-aff7-d0a34a9c80b5.mp4

🎨: move cursor in front of text to be visible in text with background

---

lively.components/muller-columns.cp.js

🎛️: actually check filtered column list length when navigating /w enter

---

lively.ide/world.js
lively.morphic/config.js

Adds a config option that allows each user to customise their preferred zoom behavior.

🧰🎨: configure zoom via config.js

---

lively.ide/js/browser/index.js

🧰: remove file size and modified date annotations in system browser

---

lively.morphic/text/morph.js

🎨: make text selection while scrolling smoother

---

lively.ide/studio/controls/border.cp.js
lively.ide/studio/controls/fill.cp.js
lively.ide/studio/properties-panel.cp.js

🧰: prevent inconsistent properties control state with opened popups

---

lively.morphic/components/policy.js
lively.morphic/morph.js

🎨: avoid policy applications cause overrides in animation context

---

lively.ide/text/search.js

🧰: fix search jumping between results while typing search term

---

lively.ide/text/rich-text-commands.js
lively.morphic/text/morph.js

🎨🧰: fix interactive editing of `Text` via direct manipulation

---

lively.2lively/interface.js
lively.ide/studio/top-bar.cp.js
lively.lang/function.js
lively.morphic/layout.js
lively.resources/src/resource.js

https://github.com/LivelyKernel/lively.next/issues/689

🧰: add not yet implemented error to component browser

---

lively.morphic/morph.js
lively.morphic/rendering/morphic-default.js
lively.morphic/rendering/renderer.js
lively.morphic/text/morph.js

🎨: allow to hide scrollbars in `Text`

---

lively.morphic/morph.js
lively.serializer2/object-pool.js

🎨📇: ensure id is properly initialized before properties are getting set

---

lively.shell/server-command.js

Although I can not verify the exact issues as encountered by @rickmcgeer, this may fix the issue reported in #750.

🐚: replace require with top level import

---

lively.components/canvas.js

🎛️: fix Canvas.fromDataURI()

---

scripts/test.js

Makes the following case easier to read:

🛠️: add newline to CI output upon package without tests

---

lively.ide/studio/dark-color-picker.cp.js
lively.ide/styling/color-picker.cp.js
lively.ide/styling/color-picker.js

https://user-images.githubusercontent.com/14252419/234050852-9abe4b90-687a-4da1-82e8-e2276c50f217.mp4

Color Picker

---

lively.morphic/rendering/morphic-default.js
lively.morphic/rendering/renderer.js

🎨: add cursor position to debug view of `Text`

---

lively.ide/js/browser/index.js

🧰: close file in system browser after file gets deleted

---

lively.project/prompts.cp.js
lively.user/user-flap.cp.js

Closes #865.
https://github.com/LivelyKernel/lively.next/assets/14252419/66d5dfec-9673-4447-9b13-4273f6f0c2c6

📂👤: make github login workflow more explicit

---

lively.ide/studio/world-browser.cp.js

Fixes some layouting issues in the search field of the projects browser.

🧰: fix some issues in the search field of the world browser

---

lively.morphic/text/morph.js

🎨: do not add border width to fixed text bounds dimensions on fit()

---

lively.morphic/rendering/font-metric.js

🎨: properly apply inverse transform to text measure node

---

lively.morphic/rendering/renderer.js

🎨: fix rendering of wrapped line selection

---

start.sh

Appears to fix the mysterious restart issues on macOS. However it is not clear how exactly.
I am open to removing some of the comments, variables. However to me it helps to understand what is going on in the script.

🛠️: switch start.sh to loop based restarting machanism

---

lively.project/project.js

📂: fix wrong usage of `Array.prototype.push()`

---

README.md
lively.shell/git-client-resource.js

https://stackoverflow.com/a/65415870/4418325

🐚🗒️: make initialization of repo compatible with older versions of git

---

lively.ide/js/browser/index.js
lively.ide/md/editor-plugin.js

🧰: only open markdown preview on button click

---

lively.morphic/components/core.js

🎨: crash if part called without policy or descriptor

---

lively.morphic/world-loading.js

🎨: fix error logging if crash in localconfig detected

---

lively.project/project.js

📂: gracefully exclude invalid projects from listings

---

lively.project/project.js

Include new files in Summary of Changes for Projects

---

lively.morphic/rendering/renderer.js

This closes #991.
This is only partially related to us switching to the new font set. More precisely, us switching unveiled some faulty assumptions that the selection code previously relied upon, which where never hit before, since we had only a very limited set of fonts.
The code is quite extensively commented and should explain what is going on here.
The crux of this issue was that we did not always caught all wrapped lines as such. The reason for this was, that we had the faulty assumption of a character in the second row of a wrapped line strictly beginning under the character directly above it in the first row of the wrapped line.
This is however not always the case, as shown in the screenshot below. When exactly this happens is dependent on the concrete font being used, its …

🎨: fix selection bug for wrapped lines

---

lively.lang/array.js
lively.project/project.js

This ensures that no duplicate entries are created and also orders the entries with ascending weight.

Fix Fontweight Dropdown for custom fonts

---

lively.project/project.js
lively.project/prompts.cp.js
lively.project/templates/deploy-pages-action.js

With this PR it becomes possible to configure projects to be deployed on every push.
It also includes a fix for a problem that made it impossible to deploy from private repositories on a paid plan, due to missing permission in the Action file.

Improved Deployment options for `lively.project`

---

lively.components/video.js

Supports muting the videos embedded via a video morph.

🎛️: support muting of videos in video morph

---

lively.ide/js/browser/index.js

By first making sure that a `.gitignore` actually exists in a way that does not try to access the file, we can silence a lot of console errors that accumulated when using the System Browser.
The performance hit due to the additional `dirList` does not seem to be too bad. Switching to lively being a `nw.js` app or implementing a cache on top of `dirList` would get rid of these performance problems once and for all.

🧰: fix `console.error` that `.gitignore` does not exist when browsing

---

.github/workflows/check-deploy-docs.yml

Fixes the currently failing doc build in the actions.

📦: pin jsdocs theme version

---

lively.user/user-flap.cp.js

Previously, it was possible to trigger multiple login operations by just clicking fast enough on the login button. This is now fixed.

👤: only start one login-operation at a time

---

lively.morphic/world-loading.js
lively.user/user-flap.cp.js

🎨👤: properly display network status in user flap on landing page

---

lively.project/project.js
lively.project/prompts.cp.js

Previously, we had information such as `repo` and various flags controlling aspects of the CI pipelines in the config of a project, even if that project never had anything to do with GitHub. As that was inconsistent, we now only add this part of the config when it is actually applicable.
@merryman I tested this, but just to be sure it would be good to have you attempt all scenarios as well:
1. Add project without remote -> change -> save -> reload -> add remote ✅ (linus) - ✅ (robin)
2. Create project with remote directly -> change -> save ✅ (linus) - ✅ (robin)
3. ~~Same as (1), but with the repository belonging to an organization.~~
4. ~~Same as (2), but with the repository belonging to an organization.~~

📂: add github specific config parts only when remote is added

---

lively.project/prompts.cp.js

Fixes the strange wobble that happens on opening of the "new project prompt".

📂: fix layout jiggle on project prompt opening

---

lively.freezer/src/bundler.js
lively.ide/components/editor.js
lively.modules/src/module.js
lively.morphic/components/core.js
lively.source-transform/index.js
lively.vm/lib/eval-support.js

Fixes an issue where local changes in component modules would not be reflected upon fast load.

🧰🎨🧩❄️🔁🖥️: fix updating of module records at reviving

---

lively.ide/js/browser/index.js

Resolves #573 as suggested by @linusha.

🧰: auto detect code entity if no or ambigious entity selected

---

lively.components/muller-columns.cp.js
lively.ide/studio/component-browser.cp.js
lively.ide/studio/controls/component.cp.js

Fixes #1056.
Fixes #1036.
Fixes #981.
Resolves #1065.

Varous improvements and fixes in component browser

---

README.md
scripts/test.sh
start-server.sh
start.sh

 🛠️🗒️: make port of lively server configurable via CLI param

---

README.md

There is a new feature for github markdown that I personally waited on since forever. Let's use it since it is awesome!
See [here](https://github.blog/changelog/2023-12-14-new-markdown-extension-alerts-provide-distinctive-styling-for-significant-content/) for more details.

🗒️: use new markdown callouts

---

lively.morphic/html-morph.js

🎨: add onOwnerChanged() super call for html morph

---

lively.freezer/src/landing-page.cp.js
lively.ide/studio/world-browser.cp.js

Up till now, the project browser displayed on the landing page would not adjust to changes in the browser window.

❄️: fix positioning of project browser in landing page

---

lively.components/prompts.cp.js
lively.git/src/js-git-webdav-fs.js

🎛️: fix edit prompt confirmation and opening issues

---

lively.ide/studio/interactive-tree.js

🧰: fix update heuristic for submorph changes in scene graph

---

lively.ide/text/multi-select-commands.js

Fix multiline cursor

---

lively.ide/studio/top-bar.cp.js

https://github.com/LivelyKernel/lively.next/assets/14252419/9723fb63-d8b4-4ce5-b3ae-509143de46c6

🧰: change default color of morphs to visibly enable hue picker

---

lively.modules/src/import-modification.js

Fixes #728.
**This issue was estimated to take 4h and took 1h.**

🧩: append inserted import to first batch of imports in module

---

lively.freezer/src/bundler.js
lively.source-transform/index.js

Fixes #1155 to the extent that I am currently aware off.
**This issue was estimated to take 1d but so far took 3h**.

❄️🔁: properly capture exported declarations in resurrection builds

---

lively.project/project.js

🚨 Fix Creation of projects failing due to missing `await`

---

lively.morphic/text/morph.js

🎨: fix 'insert icon button'

---

lively.ide/js/inspector/ui.cp.js

@merryman please confirm that this works on you system as well before merging.

🧰: fix misconfiguration of 'code editor' in `Inspector`

---

lively.ide/js/browser/index.js

Fixes #667.
@linusha I somehow cannot reproduce the broken snippet from the video any more. Maybe it still happens on your machine? That was the part I assumed to be hard...
**This issue was estimated to take 2d but actually took 0.5h**

🧰: fix non animated window theme toggle in system browser

---

lively.morphic/layout.js

🎨: prevent measuring of unaffected morphs in css layouts

---

lively.ide/styling/color-stops.cp.js
lively.ide/styling/gradient-editor.cp.js

Fixes the other half of #1205.

🧰: fix master style toggling of color stops in gradient editor

---

lively.morphic/layout.js

🎨: fix call onDomResize in grid layout

---

lively.freezer/src/landing-page.cp.js
lively.ide/studio/world-browser.cp.js
lively.morphic/helpers.js

https://github.com/LivelyKernel/lively.next/assets/14252419/d7c6b368-f1cc-43d7-89e0-72492044ce11

❄️🧰🎨: add fast load toggle button on landing page

---

lively.ide/studio/component-browser.cp.js

Another case of "How did that ever work..." :disappointed:

🧰: fix pulling of `partsbin` repository

---

lively.freezer/tools/build.loading-screen.mjs

❄️: clear console.log

---

lively.freezer/src/util/bootstrap.js

❄️: do not revive empty module

---

lively.ide/components/reconciliation.js

🧰: fix prop reconciliation for inline policies

---

lively.freezer/src/bundler.js
lively.source-transform/index.js

Fixes an issue where localconfig settings would get reset once modules got revived.

❄️🔁: capture exported object expression in resurrection builds

---

lively.morphic/components/policy.js

🎨: do not set epiMorph flag for editable components

---

lively.ide/studio/component-browser.cp.js
lively.ide/studio/controls/component.cp.js

🧰: start browsing for masters in components model at all times

---

lively.morphic/rendering/property-dom-mapping.js

🎨: fix handoff between constraint and auto layout

---

lively.components/checkbox.cp.js

🎛️: fix `LabeledCheckbox` not updating its appearance

---

lively.shell/git-client-resource.js

@merryman please make sure to read this carefully and in the best case test this locally. Using the relaunch project should suffice, just make sure to open a branch other than `blog`!

🐚: properly handle outdated branches when pushing

---

lively.halos/morph.js

👼: explicitly stop edit session if closing component via halo

---

lively.freezer/src/bundler.js
lively.modules/src/system.js
lively.source-transform/index.js

❄️🔁: properly capture namespace reexports

---

lively.ide/components/reconciliation.js
lively.morphic/layout.js

🧰🎨: reconcile layout policies on renaming morphs

---

lively.freezer/src/bundler.js

❄️: always track unresolved imports regardless of verbose config

---

lively.halos/morph.js

👼: do not remove halo on target removal during grab

---

lively.ide/studio/properties-panel.cp.js
lively.ide/studio/scene-graph.cp.js
lively.ide/studio/shared.cp.js
lively.ide/styling/color-picker.cp.js
lively.ide/tests/widget-test.js
lively.ide/value-widgets.cp.js

Various small issues with tools, now fixed.

Fix/various UI glitches in tools

---

lively.halos/morph.js

👼: set `fixedWidth`/`fixedHeight` when manipulating text morph

---

lively.components/list.js

Fixes an issues with the list morph that caused duplicate list entries with gaps for items that had the same string labels.
Can be easily observed by running `$world.execCommand("open browser", {moduleName: "js/browser/ui.cp.js", packageName: "lively.ide", codeEntity: "positionForAnchor"});` on main and observing the list of code entities.

🎛️: fix dupes in rendered list items

---

lively.project/project.js

Drastically reduce the amount of webdav lookups when opening and saving projects!

📂: exclude .git folder from potential code files in projects

---

lively.ide/js/browser/index.js
lively.ide/js/browser/ui.cp.js
lively.ide/studio/tabs.cp.js
lively.ide/world-commands.js

Opens the browser in the directory of the currently opened project, if one exists. Also makes the tabs in the browser work again.

Open Browser in opened Project and restore Tab functionality

---

.github/workflows/daily-ci-checks.yml

We involuntarily upgraded to eslint v9 which changes how configurations work. I now pinned the latest version known to be working.

Fix Daily Pipeline Check

---

lively.ide/styling/color-picker.js

🧰: fix movements of hue and opacity slider in color picker

---

lively.ide/components/reconciliation.js

Resolves an issue where deleting text that stretched across multiple text attribute would mess up the `textAndAttributes` property inside the component.

🧰: skip optimized text reconciliation for deletion of multiple attrs

---

lively.ide/studio/asset-browser.cp.js

I adjusted the dark version of the color picker to be more in tune with the dark popups. Also fixed the placeholder in the search bar, which still mentioned components for whatever reason.

Fix/asset browser UI issues

---

lively.morphic/components/policy.js

🎨: fix policy config retrieval

---

lively.ide/studio/component-browser.cp.js

🧰: show halo after component imported

---

lively.components/list.js

🎛️: fix spacing artefact on list scroll

---

lively.morphic/components/policy.js

🎨: fix conflicting extent application via policy and hugging behavior

---

lively.ide/styling/color-picker.js

I have not idea what happened here.  Maybe something that happened accidentally through a rebase?

🧰: fix broken code in field picker position getter

---

lively.morphic/html-morph.js

Adds some new behavior to the html morph which allows us to configure it to fit its extent to its contents (similar to the text morphs).

🎨: add support for fitting html morph to contents

---

lively.morphic/assets/fonts/fonts.css

We only used black-and-white until now, but I'd like to have the colored versions for the website.

🎨: add "Noto Color Emoji" font

---

lively.ide/js/inspector/index.js
lively.ide/js/inspector/ui.cp.js

🧰: fix broken button layout in inspector

---

lively.ide/studio/world-browser.cp.js

🧰: remove deprecated sorting feature in world list

---

lively.components/muller-columns.cp.js

🎛️: fix updating of muller columns if child count the same

---

lively.ide/components/reconciliation.js

🧰: resort to default patch if entire document replaced

---

lively.components/menus.js

🎛️: adjust styling of menu deviders

---

lively.ide/components/helpers.js
lively.ide/studio/controls/body.cp.js
lively.ide/studio/controls/popups.cp.js
lively.morphic/rendering/property-dom-mapping.js

https://github.com/LivelyKernel/lively.next/assets/1296388/19d5e279-5e66-4b1e-bec9-514930beeda9

🎨: add support for backdrop blur

---

lively.ide/js/workspace.js
lively.ide/shell/workspace.js
lively.morphic/config.js

I got sick and tired of another workspace that did not have the proper text hug configuration, so now we just handle it via config.

🧰🎨: ensure proper resizing for ALL workspace once and for all

---

lively.morphic/config.js

Revision to a completely non functional #1614 🤡

🎨: move workspace props into correct place in config

---

lively.morphic/rendering/font-metric.js

Fixes an annoying issue of the text layout, where it would consider some characters not to wrap unlike the browsers leading to unusable code editors. @linusha.

🎨: fix rounding error in char wrapping

---

lively.morphic/text/morph.js

Simple yet effective way to deal with  #1561. What do you think @linusha?

🎨: always return line wrapping as "no wrap" if hugging enabled

---

lively.morphic/html-morph.js

Fixes inaccuracies caused by the previous implementation strategy for html morph fitting.

🎨: fit html morph via css and resize observer

---

lively.lang/function.js
lively.lang/tests/function-test.js

So that we do not forget about this - as I opened the PR, you'll need to approve it yourself @merryman.

📙: fix premature reset on debounce named with immediate

---

lively.project/prompts.cp.js

📂: fix layout in settings prompt

---

.github/workflows/check-deploy-docs.yml

One of the action steps we used relied on another action which was deprecated. I updated the relevant actions steps.

Fix Docs Build Action

---

lively.morphic/morph.js

🎨: fix scrollExtent and scrollbarVisible prop when scrollbars hidden

---

lively.morphic/rendering/font-metric.js

🎨: properly factor in padding when computing line breaks by-words

---

lively.morphic/components/policy.js
lively.morphic/tests/components-test.cp.js

🎨: prevent contradicting merge of text props during component init

---

lively.modules/src/export-lookup.js

🧩: fix export lookup methods for frozen modules

---

lively.components/loading-indicator.cp.js

🎛️: fix button alignment of loading indicator
